// Code generated by pipeline.py. DO NOT EDIT manually.

package api

import (
	"context"

	"github.com/google/uuid"
)

// ClientExt wraps the base Client with organized sub-client access.
// Use controller methods (e.g., client.Users().GetUserById()) to call API operations.
type ClientExt struct {
	client                         *Client
	apiTokens                      *ApiTokensClient
	auth                           *AuthClient
	bandwidthStatsNodes            *BandwidthStatsNodesClient
	bandwidthStatsUsers            *BandwidthStatsUsersClient
	configProfile                  *ConfigProfileClient
	connections                    *ConnectionsClient
	externalSquad                  *ExternalSquadClient
	hosts                          *HostsClient
	hostsBulkActions               *HostsBulkActionsClient
	hwidUserDevices                *HwidUserDevicesClient
	infraBilling                   *InfraBillingClient
	internalSquad                  *InternalSquadClient
	internalSquadStats             *InternalSquadStatsClient
	keygen                         *KeygenClient
	metadata                       *MetadataClient
	nodeIntegration                *NodeIntegrationClient
	nodePlugin                     *NodePluginClient
	nodes                          *NodesClient
	nodesUsageHistory              *NodesUsageHistoryClient
	passkey                        *PasskeyClient
	remnawaveSettings              *RemnawaveSettingsClient
	snippets                       *SnippetsClient
	subscription                   *SubscriptionClient
	subscriptionPageConfig         *SubscriptionPageConfigClient
	subscriptionSettings           *SubscriptionSettingsClient
	subscriptionTemplate           *SubscriptionTemplateClient
	subscriptions                  *SubscriptionsClient
	system                         *SystemClient
	torrentBlockerReports          *TorrentBlockerReportsClient
	userSubscriptionRequestHistory *UserSubscriptionRequestHistoryClient
	users                          *UsersClient
	usersBulkActions               *UsersBulkActionsClient
}

// NewClientExt creates a new ClientExt wrapper.
func NewClientExt(client *Client) *ClientExt {
	return &ClientExt{
		client:                         client,
		apiTokens:                      NewApiTokensClient(client),
		auth:                           NewAuthClient(client),
		bandwidthStatsNodes:            NewBandwidthStatsNodesClient(client),
		bandwidthStatsUsers:            NewBandwidthStatsUsersClient(client),
		configProfile:                  NewConfigProfileClient(client),
		connections:                    NewConnectionsClient(client),
		externalSquad:                  NewExternalSquadClient(client),
		hosts:                          NewHostsClient(client),
		hostsBulkActions:               NewHostsBulkActionsClient(client),
		hwidUserDevices:                NewHwidUserDevicesClient(client),
		infraBilling:                   NewInfraBillingClient(client),
		internalSquad:                  NewInternalSquadClient(client),
		internalSquadStats:             NewInternalSquadStatsClient(client),
		keygen:                         NewKeygenClient(client),
		metadata:                       NewMetadataClient(client),
		nodeIntegration:                NewNodeIntegrationClient(client),
		nodePlugin:                     NewNodePluginClient(client),
		nodes:                          NewNodesClient(client),
		nodesUsageHistory:              NewNodesUsageHistoryClient(client),
		passkey:                        NewPasskeyClient(client),
		remnawaveSettings:              NewRemnawaveSettingsClient(client),
		snippets:                       NewSnippetsClient(client),
		subscription:                   NewSubscriptionClient(client),
		subscriptionPageConfig:         NewSubscriptionPageConfigClient(client),
		subscriptionSettings:           NewSubscriptionSettingsClient(client),
		subscriptionTemplate:           NewSubscriptionTemplateClient(client),
		subscriptions:                  NewSubscriptionsClient(client),
		system:                         NewSystemClient(client),
		torrentBlockerReports:          NewTorrentBlockerReportsClient(client),
		userSubscriptionRequestHistory: NewUserSubscriptionRequestHistoryClient(client),
		users:                          NewUsersClient(client),
		usersBulkActions:               NewUsersBulkActionsClient(client),
	}
}

// Client returns the underlying ogen Client.
func (ce *ClientExt) Client() *Client {
	return ce.client
}

// ApiTokens returns the ApiTokensClient.
func (ce *ClientExt) ApiTokens() *ApiTokensClient {
	return ce.apiTokens
}

// Auth returns the AuthClient.
func (ce *ClientExt) Auth() *AuthClient {
	return ce.auth
}

// BandwidthStatsNodes returns the BandwidthStatsNodesClient.
func (ce *ClientExt) BandwidthStatsNodes() *BandwidthStatsNodesClient {
	return ce.bandwidthStatsNodes
}

// BandwidthStatsUsers returns the BandwidthStatsUsersClient.
func (ce *ClientExt) BandwidthStatsUsers() *BandwidthStatsUsersClient {
	return ce.bandwidthStatsUsers
}

// ConfigProfile returns the ConfigProfileClient.
func (ce *ClientExt) ConfigProfile() *ConfigProfileClient {
	return ce.configProfile
}

// Connections returns the ConnectionsClient.
func (ce *ClientExt) Connections() *ConnectionsClient {
	return ce.connections
}

// ExternalSquad returns the ExternalSquadClient.
func (ce *ClientExt) ExternalSquad() *ExternalSquadClient {
	return ce.externalSquad
}

// Hosts returns the HostsClient.
func (ce *ClientExt) Hosts() *HostsClient {
	return ce.hosts
}

// HostsBulkActions returns the HostsBulkActionsClient.
func (ce *ClientExt) HostsBulkActions() *HostsBulkActionsClient {
	return ce.hostsBulkActions
}

// HwidUserDevices returns the HwidUserDevicesClient.
func (ce *ClientExt) HwidUserDevices() *HwidUserDevicesClient {
	return ce.hwidUserDevices
}

// InfraBilling returns the InfraBillingClient.
func (ce *ClientExt) InfraBilling() *InfraBillingClient {
	return ce.infraBilling
}

// InternalSquad returns the InternalSquadClient.
func (ce *ClientExt) InternalSquad() *InternalSquadClient {
	return ce.internalSquad
}

// InternalSquadStats returns the InternalSquadStatsClient.
func (ce *ClientExt) InternalSquadStats() *InternalSquadStatsClient {
	return ce.internalSquadStats
}

// Keygen returns the KeygenClient.
func (ce *ClientExt) Keygen() *KeygenClient {
	return ce.keygen
}

// Metadata returns the MetadataClient.
func (ce *ClientExt) Metadata() *MetadataClient {
	return ce.metadata
}

// NodeIntegration returns the NodeIntegrationClient.
func (ce *ClientExt) NodeIntegration() *NodeIntegrationClient {
	return ce.nodeIntegration
}

// NodePlugin returns the NodePluginClient.
func (ce *ClientExt) NodePlugin() *NodePluginClient {
	return ce.nodePlugin
}

// Nodes returns the NodesClient.
func (ce *ClientExt) Nodes() *NodesClient {
	return ce.nodes
}

// NodesUsageHistory returns the NodesUsageHistoryClient.
func (ce *ClientExt) NodesUsageHistory() *NodesUsageHistoryClient {
	return ce.nodesUsageHistory
}

// Passkey returns the PasskeyClient.
func (ce *ClientExt) Passkey() *PasskeyClient {
	return ce.passkey
}

// RemnawaveSettings returns the RemnawaveSettingsClient.
func (ce *ClientExt) RemnawaveSettings() *RemnawaveSettingsClient {
	return ce.remnawaveSettings
}

// Snippets returns the SnippetsClient.
func (ce *ClientExt) Snippets() *SnippetsClient {
	return ce.snippets
}

// Subscription returns the SubscriptionClient.
func (ce *ClientExt) Subscription() *SubscriptionClient {
	return ce.subscription
}

// SubscriptionPageConfig returns the SubscriptionPageConfigClient.
func (ce *ClientExt) SubscriptionPageConfig() *SubscriptionPageConfigClient {
	return ce.subscriptionPageConfig
}

// SubscriptionSettings returns the SubscriptionSettingsClient.
func (ce *ClientExt) SubscriptionSettings() *SubscriptionSettingsClient {
	return ce.subscriptionSettings
}

// SubscriptionTemplate returns the SubscriptionTemplateClient.
func (ce *ClientExt) SubscriptionTemplate() *SubscriptionTemplateClient {
	return ce.subscriptionTemplate
}

// Subscriptions returns the SubscriptionsClient.
func (ce *ClientExt) Subscriptions() *SubscriptionsClient {
	return ce.subscriptions
}

// System returns the SystemClient.
func (ce *ClientExt) System() *SystemClient {
	return ce.system
}

// TorrentBlockerReports returns the TorrentBlockerReportsClient.
func (ce *ClientExt) TorrentBlockerReports() *TorrentBlockerReportsClient {
	return ce.torrentBlockerReports
}

// UserSubscriptionRequestHistory returns the UserSubscriptionRequestHistoryClient.
func (ce *ClientExt) UserSubscriptionRequestHistory() *UserSubscriptionRequestHistoryClient {
	return ce.userSubscriptionRequestHistory
}

// Users returns the UsersClient.
func (ce *ClientExt) Users() *UsersClient {
	return ce.users
}

// UsersBulkActions returns the UsersBulkActionsClient.
func (ce *ClientExt) UsersBulkActions() *UsersBulkActionsClient {
	return ce.usersBulkActions
}

// ApiTokensClient provides ApiTokens operations.
type ApiTokensClient struct {
	client *Client
}

// NewApiTokensClient creates a new ApiTokensClient.
func NewApiTokensClient(client *Client) *ApiTokensClient {
	return &ApiTokensClient{client: client}
}

// CreateApiToken calls ApiTokens_createApiToken.
func (sc *ApiTokensClient) CreateApiToken(ctx context.Context, request *CreateApiTokenBody, options ...RequestOption) (ApiTokensCreateApiTokenRes, error) {
	return sc.client.ApiTokensCreateApiToken(ctx, request, options...)
}

// DeleteApiToken calls ApiTokens_deleteApiToken.
func (sc *ApiTokensClient) DeleteApiToken(ctx context.Context, uuidValue string, options ...RequestOption) (ApiTokensDeleteApiTokenRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ApiTokensDeleteApiTokenRes
		return zero0, err
	}

	return sc.client.ApiTokensDeleteApiToken(ctx, ApiTokensDeleteApiTokenParams{
		UUID: parsedUUID,
	}, options...)
}

// GetApiTokens calls ApiTokens_getApiTokens.
func (sc *ApiTokensClient) GetApiTokens(ctx context.Context, options ...RequestOption) (ApiTokensGetApiTokensRes, error) {
	return sc.client.ApiTokensGetApiTokens(ctx, options...)
}

// GetScopes calls ApiTokens_getScopes.
func (sc *ApiTokensClient) GetScopes(ctx context.Context, options ...RequestOption) (ApiTokensGetScopesRes, error) {
	return sc.client.ApiTokensGetScopes(ctx, options...)
}

// AuthClient provides Auth operations.
type AuthClient struct {
	client *Client
}

// NewAuthClient creates a new AuthClient.
func NewAuthClient(client *Client) *AuthClient {
	return &AuthClient{client: client}
}

// GetStatus calls Auth_getStatus.
func (sc *AuthClient) GetStatus(ctx context.Context, options ...RequestOption) (AuthGetStatusRes, error) {
	return sc.client.AuthGetStatus(ctx, options...)
}

// Login calls Auth_login.
func (sc *AuthClient) Login(ctx context.Context, request *LoginBody, options ...RequestOption) (AuthLoginRes, error) {
	return sc.client.AuthLogin(ctx, request, options...)
}

// Oauth2Authorize calls Auth_oauth2Authorize.
func (sc *AuthClient) Oauth2Authorize(ctx context.Context, request *OAuth2AuthorizeBody, options ...RequestOption) (AuthOauth2AuthorizeRes, error) {
	return sc.client.AuthOauth2Authorize(ctx, request, options...)
}

// Oauth2Callback calls Auth_oauth2Callback.
func (sc *AuthClient) Oauth2Callback(ctx context.Context, request *OAuth2CallbackBody, options ...RequestOption) (AuthOauth2CallbackRes, error) {
	return sc.client.AuthOauth2Callback(ctx, request, options...)
}

// PasskeyAuthenticationOptions calls Auth_passkeyAuthenticationOptions.
func (sc *AuthClient) PasskeyAuthenticationOptions(ctx context.Context, options ...RequestOption) (AuthPasskeyAuthenticationOptionsRes, error) {
	return sc.client.AuthPasskeyAuthenticationOptions(ctx, options...)
}

// PasskeyAuthenticationVerify calls Auth_passkeyAuthenticationVerify.
func (sc *AuthClient) PasskeyAuthenticationVerify(ctx context.Context, request *PasskeyOptions, options ...RequestOption) (AuthPasskeyAuthenticationVerifyRes, error) {
	return sc.client.AuthPasskeyAuthenticationVerify(ctx, request, options...)
}

// Register calls Auth_register.
func (sc *AuthClient) Register(ctx context.Context, request *RegisterBody, options ...RequestOption) (AuthRegisterRes, error) {
	return sc.client.AuthRegister(ctx, request, options...)
}

// BandwidthStatsNodesClient provides BandwidthStatsNodes operations.
type BandwidthStatsNodesClient struct {
	client *Client
}

// NewBandwidthStatsNodesClient creates a new BandwidthStatsNodesClient.
func NewBandwidthStatsNodesClient(client *Client) *BandwidthStatsNodesClient {
	return &BandwidthStatsNodesClient{client: client}
}

// GetNodeUsage calls BandwidthStatsNodes_getNodeUsage.
func (sc *BandwidthStatsNodesClient) GetNodeUsage(ctx context.Context, request *GetNodeUsageBody, params BandwidthStatsNodesGetNodeUsageParams, options ...RequestOption) (BandwidthStatsNodesGetNodeUsageRes, error) {
	return sc.client.BandwidthStatsNodesGetNodeUsage(ctx, request, params, options...)
}

// GetStatsNodeUsersUsage calls BandwidthStatsNodes_getStatsNodeUsersUsage.
func (sc *BandwidthStatsNodesClient) GetStatsNodeUsersUsage(ctx context.Context, params BandwidthStatsNodesGetStatsNodeUsersUsageParams, options ...RequestOption) (BandwidthStatsNodesGetStatsNodeUsersUsageRes, error) {
	return sc.client.BandwidthStatsNodesGetStatsNodeUsersUsage(ctx, params, options...)
}

// GetStatsNodesUsersUsage calls BandwidthStatsNodes_getStatsNodesUsersUsage.
func (sc *BandwidthStatsNodesClient) GetStatsNodesUsersUsage(ctx context.Context, request *GetStatsNodesUsersUsageBody, params BandwidthStatsNodesGetStatsNodesUsersUsageParams, options ...RequestOption) (BandwidthStatsNodesGetStatsNodesUsersUsageRes, error) {
	return sc.client.BandwidthStatsNodesGetStatsNodesUsersUsage(ctx, request, params, options...)
}

// BandwidthStatsUsersClient provides BandwidthStatsUsers operations.
type BandwidthStatsUsersClient struct {
	client *Client
}

// NewBandwidthStatsUsersClient creates a new BandwidthStatsUsersClient.
func NewBandwidthStatsUsersClient(client *Client) *BandwidthStatsUsersClient {
	return &BandwidthStatsUsersClient{client: client}
}

// GetStatsNodesUsage calls BandwidthStatsUsers_getStatsNodesUsage.
func (sc *BandwidthStatsUsersClient) GetStatsNodesUsage(ctx context.Context, params BandwidthStatsUsersGetStatsNodesUsageParams, options ...RequestOption) (BandwidthStatsUsersGetStatsNodesUsageRes, error) {
	return sc.client.BandwidthStatsUsersGetStatsNodesUsage(ctx, params, options...)
}

// ConfigProfileClient provides ConfigProfile operations.
type ConfigProfileClient struct {
	client *Client
}

// NewConfigProfileClient creates a new ConfigProfileClient.
func NewConfigProfileClient(client *Client) *ConfigProfileClient {
	return &ConfigProfileClient{client: client}
}

// CreateConfigProfile calls ConfigProfile_createConfigProfile.
func (sc *ConfigProfileClient) CreateConfigProfile(ctx context.Context, request *CreateConfigProfileBody, options ...RequestOption) (ConfigProfileCreateConfigProfileRes, error) {
	return sc.client.ConfigProfileCreateConfigProfile(ctx, request, options...)
}

// DeleteConfigProfileByUuid calls ConfigProfile_deleteConfigProfileByUuid.
func (sc *ConfigProfileClient) DeleteConfigProfileByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (ConfigProfileDeleteConfigProfileByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ConfigProfileDeleteConfigProfileByUuidRes
		return zero0, err
	}

	return sc.client.ConfigProfileDeleteConfigProfileByUuid(ctx, ConfigProfileDeleteConfigProfileByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetAllInbounds calls ConfigProfile_getAllInbounds.
func (sc *ConfigProfileClient) GetAllInbounds(ctx context.Context, options ...RequestOption) (ConfigProfileGetAllInboundsRes, error) {
	return sc.client.ConfigProfileGetAllInbounds(ctx, options...)
}

// GetComputedConfigProfileByUuid calls ConfigProfile_getComputedConfigProfileByUuid.
func (sc *ConfigProfileClient) GetComputedConfigProfileByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (ConfigProfileGetComputedConfigProfileByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ConfigProfileGetComputedConfigProfileByUuidRes
		return zero0, err
	}

	return sc.client.ConfigProfileGetComputedConfigProfileByUuid(ctx, ConfigProfileGetComputedConfigProfileByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetConfigProfileByUuid calls ConfigProfile_getConfigProfileByUuid.
func (sc *ConfigProfileClient) GetConfigProfileByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (ConfigProfileGetConfigProfileByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ConfigProfileGetConfigProfileByUuidRes
		return zero0, err
	}

	return sc.client.ConfigProfileGetConfigProfileByUuid(ctx, ConfigProfileGetConfigProfileByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetConfigProfiles calls ConfigProfile_getConfigProfiles.
func (sc *ConfigProfileClient) GetConfigProfiles(ctx context.Context, options ...RequestOption) (ConfigProfileGetConfigProfilesRes, error) {
	return sc.client.ConfigProfileGetConfigProfiles(ctx, options...)
}

// GetInboundsByProfileUuid calls ConfigProfile_getInboundsByProfileUuid.
func (sc *ConfigProfileClient) GetInboundsByProfileUuid(ctx context.Context, uuidValue string, options ...RequestOption) (ConfigProfileGetInboundsByProfileUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ConfigProfileGetInboundsByProfileUuidRes
		return zero0, err
	}

	return sc.client.ConfigProfileGetInboundsByProfileUuid(ctx, ConfigProfileGetInboundsByProfileUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetTags calls ConfigProfile_getTags.
func (sc *ConfigProfileClient) GetTags(ctx context.Context, options ...RequestOption) (ConfigProfileGetTagsRes, error) {
	return sc.client.ConfigProfileGetTags(ctx, options...)
}

// ReorderConfigProfiles calls ConfigProfile_reorderConfigProfiles.
func (sc *ConfigProfileClient) ReorderConfigProfiles(ctx context.Context, request *ReorderConfigProfilesBody, options ...RequestOption) (ConfigProfileReorderConfigProfilesRes, error) {
	return sc.client.ConfigProfileReorderConfigProfiles(ctx, request, options...)
}

// SetTags calls ConfigProfile_setTags.
func (sc *ConfigProfileClient) SetTags(ctx context.Context, request *SetConfigProfilesTagsBody, options ...RequestOption) (ConfigProfileSetTagsRes, error) {
	return sc.client.ConfigProfileSetTags(ctx, request, options...)
}

// UpdateConfigProfile calls ConfigProfile_updateConfigProfile.
func (sc *ConfigProfileClient) UpdateConfigProfile(ctx context.Context, request *UpdateConfigProfileBody, options ...RequestOption) (ConfigProfileUpdateConfigProfileRes, error) {
	return sc.client.ConfigProfileUpdateConfigProfile(ctx, request, options...)
}

// ConnectionsClient provides Connections operations.
type ConnectionsClient struct {
	client *Client
}

// NewConnectionsClient creates a new ConnectionsClient.
func NewConnectionsClient(client *Client) *ConnectionsClient {
	return &ConnectionsClient{client: client}
}

// ConnectionsByNode calls Connections_connectionsByNode.
func (sc *ConnectionsClient) ConnectionsByNode(ctx context.Context, nodeuuid string, options ...RequestOption) (ConnectionsConnectionsByNodeRes, error) {
	parsedNodeUuid, err := uuid.Parse(nodeuuid)
	if err != nil {
		var zero0 ConnectionsConnectionsByNodeRes
		return zero0, err
	}

	return sc.client.ConnectionsConnectionsByNode(ctx, ConnectionsConnectionsByNodeParams{
		NodeUuid: parsedNodeUuid,
	}, options...)
}

// ConnectionsByNodeResult calls Connections_connectionsByNodeResult.
func (sc *ConnectionsClient) ConnectionsByNodeResult(ctx context.Context, jobid string, options ...RequestOption) (ConnectionsConnectionsByNodeResultRes, error) {

	return sc.client.ConnectionsConnectionsByNodeResult(ctx, ConnectionsConnectionsByNodeResultParams{
		JobId: jobid,
	}, options...)
}

// ConnectionsByUser calls Connections_connectionsByUser.
func (sc *ConnectionsClient) ConnectionsByUser(ctx context.Context, userid int, options ...RequestOption) (ConnectionsConnectionsByUserRes, error) {

	return sc.client.ConnectionsConnectionsByUser(ctx, ConnectionsConnectionsByUserParams{
		UserId: userid,
	}, options...)
}

// ConnectionsByUserResult calls Connections_connectionsByUserResult.
func (sc *ConnectionsClient) ConnectionsByUserResult(ctx context.Context, jobid string, options ...RequestOption) (ConnectionsConnectionsByUserResultRes, error) {

	return sc.client.ConnectionsConnectionsByUserResult(ctx, ConnectionsConnectionsByUserResultParams{
		JobId: jobid,
	}, options...)
}

// DropConnections calls Connections_dropConnections.
func (sc *ConnectionsClient) DropConnections(ctx context.Context, request *DropConnectionsBody, options ...RequestOption) (ConnectionsDropConnectionsRes, error) {
	return sc.client.ConnectionsDropConnections(ctx, request, options...)
}

// GeocheckByNode calls Connections_geocheckByNode.
func (sc *ConnectionsClient) GeocheckByNode(ctx context.Context, request *GeocheckByNodeBody, nodeuuid string, options ...RequestOption) (ConnectionsGeocheckByNodeRes, error) {
	parsedNodeUuid, err := uuid.Parse(nodeuuid)
	if err != nil {
		var zero0 ConnectionsGeocheckByNodeRes
		return zero0, err
	}

	return sc.client.ConnectionsGeocheckByNode(ctx, request, ConnectionsGeocheckByNodeParams{
		NodeUuid: parsedNodeUuid,
	}, options...)
}

// GeocheckByNodeResult calls Connections_geocheckByNodeResult.
func (sc *ConnectionsClient) GeocheckByNodeResult(ctx context.Context, jobid string, options ...RequestOption) (ConnectionsGeocheckByNodeResultRes, error) {

	return sc.client.ConnectionsGeocheckByNodeResult(ctx, ConnectionsGeocheckByNodeResultParams{
		JobId: jobid,
	}, options...)
}

// ExternalSquadClient provides ExternalSquad operations.
type ExternalSquadClient struct {
	client *Client
}

// NewExternalSquadClient creates a new ExternalSquadClient.
func NewExternalSquadClient(client *Client) *ExternalSquadClient {
	return &ExternalSquadClient{client: client}
}

// AddUsersToExternalSquad calls ExternalSquad_addUsersToExternalSquad.
func (sc *ExternalSquadClient) AddUsersToExternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (ExternalSquadAddUsersToExternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ExternalSquadAddUsersToExternalSquadRes
		return zero0, err
	}

	return sc.client.ExternalSquadAddUsersToExternalSquad(ctx, ExternalSquadAddUsersToExternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// CreateExternalSquad calls ExternalSquad_createExternalSquad.
func (sc *ExternalSquadClient) CreateExternalSquad(ctx context.Context, request *CreateExternalSquadBody, options ...RequestOption) (ExternalSquadCreateExternalSquadRes, error) {
	return sc.client.ExternalSquadCreateExternalSquad(ctx, request, options...)
}

// DeleteExternalSquad calls ExternalSquad_deleteExternalSquad.
func (sc *ExternalSquadClient) DeleteExternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (ExternalSquadDeleteExternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ExternalSquadDeleteExternalSquadRes
		return zero0, err
	}

	return sc.client.ExternalSquadDeleteExternalSquad(ctx, ExternalSquadDeleteExternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// GetExternalSquadByUuid calls ExternalSquad_getExternalSquadByUuid.
func (sc *ExternalSquadClient) GetExternalSquadByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (ExternalSquadGetExternalSquadByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ExternalSquadGetExternalSquadByUuidRes
		return zero0, err
	}

	return sc.client.ExternalSquadGetExternalSquadByUuid(ctx, ExternalSquadGetExternalSquadByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetExternalSquads calls ExternalSquad_getExternalSquads.
func (sc *ExternalSquadClient) GetExternalSquads(ctx context.Context, options ...RequestOption) (ExternalSquadGetExternalSquadsRes, error) {
	return sc.client.ExternalSquadGetExternalSquads(ctx, options...)
}

// GetTags calls ExternalSquad_getTags.
func (sc *ExternalSquadClient) GetTags(ctx context.Context, options ...RequestOption) (ExternalSquadGetTagsRes, error) {
	return sc.client.ExternalSquadGetTags(ctx, options...)
}

// RemoveUsersFromExternalSquad calls ExternalSquad_removeUsersFromExternalSquad.
func (sc *ExternalSquadClient) RemoveUsersFromExternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (ExternalSquadRemoveUsersFromExternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 ExternalSquadRemoveUsersFromExternalSquadRes
		return zero0, err
	}

	return sc.client.ExternalSquadRemoveUsersFromExternalSquad(ctx, ExternalSquadRemoveUsersFromExternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// ReorderExternalSquads calls ExternalSquad_reorderExternalSquads.
func (sc *ExternalSquadClient) ReorderExternalSquads(ctx context.Context, request *ReorderExternalSquadsBody, options ...RequestOption) (ExternalSquadReorderExternalSquadsRes, error) {
	return sc.client.ExternalSquadReorderExternalSquads(ctx, request, options...)
}

// SetTags calls ExternalSquad_setTags.
func (sc *ExternalSquadClient) SetTags(ctx context.Context, request *SetExternalSquadsTagsBody, options ...RequestOption) (ExternalSquadSetTagsRes, error) {
	return sc.client.ExternalSquadSetTags(ctx, request, options...)
}

// UpdateExternalSquad calls ExternalSquad_updateExternalSquad.
func (sc *ExternalSquadClient) UpdateExternalSquad(ctx context.Context, request *UpdateExternalSquadBody, options ...RequestOption) (ExternalSquadUpdateExternalSquadRes, error) {
	return sc.client.ExternalSquadUpdateExternalSquad(ctx, request, options...)
}

// HostsClient provides Hosts operations.
type HostsClient struct {
	client *Client
}

// NewHostsClient creates a new HostsClient.
func NewHostsClient(client *Client) *HostsClient {
	return &HostsClient{client: client}
}

// CreateHost calls Hosts_createHost.
func (sc *HostsClient) CreateHost(ctx context.Context, request *CreateHostBody, options ...RequestOption) (HostsCreateHostRes, error) {
	return sc.client.HostsCreateHost(ctx, request, options...)
}

// DeleteHost calls Hosts_deleteHost.
func (sc *HostsClient) DeleteHost(ctx context.Context, uuidValue string, options ...RequestOption) (HostsDeleteHostRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 HostsDeleteHostRes
		return zero0, err
	}

	return sc.client.HostsDeleteHost(ctx, HostsDeleteHostParams{
		UUID: parsedUUID,
	}, options...)
}

// GetHosts calls Hosts_getHosts.
func (sc *HostsClient) GetHosts(ctx context.Context, options ...RequestOption) (HostsGetHostsRes, error) {
	return sc.client.HostsGetHosts(ctx, options...)
}

// GetHostsTags calls Hosts_getHostsTags.
func (sc *HostsClient) GetHostsTags(ctx context.Context, options ...RequestOption) (HostsGetHostsTagsRes, error) {
	return sc.client.HostsGetHostsTags(ctx, options...)
}

// GetOneHost calls Hosts_getOneHost.
func (sc *HostsClient) GetOneHost(ctx context.Context, uuidValue string, options ...RequestOption) (HostsGetOneHostRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 HostsGetOneHostRes
		return zero0, err
	}

	return sc.client.HostsGetOneHost(ctx, HostsGetOneHostParams{
		UUID: parsedUUID,
	}, options...)
}

// ReorderHosts calls Hosts_reorderHosts.
func (sc *HostsClient) ReorderHosts(ctx context.Context, request *ReorderHostsBody, options ...RequestOption) (HostsReorderHostsRes, error) {
	return sc.client.HostsReorderHosts(ctx, request, options...)
}

// UpdateHost calls Hosts_updateHost.
func (sc *HostsClient) UpdateHost(ctx context.Context, request *UpdateHostBody, options ...RequestOption) (HostsUpdateHostRes, error) {
	return sc.client.HostsUpdateHost(ctx, request, options...)
}

// HostsBulkActionsClient provides HostsBulkActions operations.
type HostsBulkActionsClient struct {
	client *Client
}

// NewHostsBulkActionsClient creates a new HostsBulkActionsClient.
func NewHostsBulkActionsClient(client *Client) *HostsBulkActionsClient {
	return &HostsBulkActionsClient{client: client}
}

// DeleteHosts calls HostsBulkActions_deleteHosts.
func (sc *HostsBulkActionsClient) DeleteHosts(ctx context.Context, request *HostsBodyBulkRequest, options ...RequestOption) (HostsBulkActionsDeleteHostsRes, error) {
	return sc.client.HostsBulkActionsDeleteHosts(ctx, request, options...)
}

// DisableHosts calls HostsBulkActions_disableHosts.
func (sc *HostsBulkActionsClient) DisableHosts(ctx context.Context, request *HostsBodyBulkRequest, options ...RequestOption) (HostsBulkActionsDisableHostsRes, error) {
	return sc.client.HostsBulkActionsDisableHosts(ctx, request, options...)
}

// EnableHosts calls HostsBulkActions_enableHosts.
func (sc *HostsBulkActionsClient) EnableHosts(ctx context.Context, request *HostsBodyBulkRequest, options ...RequestOption) (HostsBulkActionsEnableHostsRes, error) {
	return sc.client.HostsBulkActionsEnableHosts(ctx, request, options...)
}

// SetPortToHosts calls HostsBulkActions_setPortToHosts.
func (sc *HostsBulkActionsClient) SetPortToHosts(ctx context.Context, request *UpdateManyHostsBody, options ...RequestOption) (HostsBulkActionsSetPortToHostsRes, error) {
	return sc.client.HostsBulkActionsSetPortToHosts(ctx, request, options...)
}

// HwidUserDevicesClient provides HwidUserDevices operations.
type HwidUserDevicesClient struct {
	client *Client
}

// NewHwidUserDevicesClient creates a new HwidUserDevicesClient.
func NewHwidUserDevicesClient(client *Client) *HwidUserDevicesClient {
	return &HwidUserDevicesClient{client: client}
}

// CreateUserHwidDevice calls HwidUserDevices_createUserHwidDevice.
func (sc *HwidUserDevicesClient) CreateUserHwidDevice(ctx context.Context, request *CreateUserHwidDeviceBody, options ...RequestOption) (HwidUserDevicesCreateUserHwidDeviceRes, error) {
	return sc.client.HwidUserDevicesCreateUserHwidDevice(ctx, request, options...)
}

// DeleteAllUserHwidDevices calls HwidUserDevices_deleteAllUserHwidDevices.
func (sc *HwidUserDevicesClient) DeleteAllUserHwidDevices(ctx context.Context, request *DeleteAllUserHwidDevicesBody, options ...RequestOption) (HwidUserDevicesDeleteAllUserHwidDevicesRes, error) {
	return sc.client.HwidUserDevicesDeleteAllUserHwidDevices(ctx, request, options...)
}

// DeleteUserHwidDevice calls HwidUserDevices_deleteUserHwidDevice.
func (sc *HwidUserDevicesClient) DeleteUserHwidDevice(ctx context.Context, request *DeleteUserHwidDeviceBody, options ...RequestOption) (HwidUserDevicesDeleteUserHwidDeviceRes, error) {
	return sc.client.HwidUserDevicesDeleteUserHwidDevice(ctx, request, options...)
}

// GetAllUsersWithParams calls HwidUserDevices_getAllUsers.
func (sc *HwidUserDevicesClient) GetAllUsersWithParams(ctx context.Context, params HwidUserDevicesGetAllUsersParams, options ...RequestOption) (HwidUserDevicesGetAllUsersRes, error) {
	return sc.client.HwidUserDevicesGetAllUsers(ctx, params, options...)
}

// GetAllUsers lists results with simple offset pagination.
func (sc *HwidUserDevicesClient) GetAllUsers(ctx context.Context, start int, size int, options ...RequestOption) (HwidUserDevicesGetAllUsersRes, error) {
	return sc.GetAllUsersWithParams(ctx, HwidUserDevicesGetAllUsersParams{
		Start: NewOptInt(start),
		Size:  NewOptInt(size),
	}, options...)
}

// GetHwidDevicesStats calls HwidUserDevices_getHwidDevicesStats.
func (sc *HwidUserDevicesClient) GetHwidDevicesStats(ctx context.Context, options ...RequestOption) (HwidUserDevicesGetHwidDevicesStatsRes, error) {
	return sc.client.HwidUserDevicesGetHwidDevicesStats(ctx, options...)
}

// GetTopUsersByHwidDevices calls HwidUserDevices_getTopUsersByHwidDevices.
func (sc *HwidUserDevicesClient) GetTopUsersByHwidDevices(ctx context.Context, params HwidUserDevicesGetTopUsersByHwidDevicesParams, options ...RequestOption) (HwidUserDevicesGetTopUsersByHwidDevicesRes, error) {
	return sc.client.HwidUserDevicesGetTopUsersByHwidDevices(ctx, params, options...)
}

// GetUserHwidDevices calls HwidUserDevices_getUserHwidDevices.
func (sc *HwidUserDevicesClient) GetUserHwidDevices(ctx context.Context, userid int, options ...RequestOption) (HwidUserDevicesGetUserHwidDevicesRes, error) {

	return sc.client.HwidUserDevicesGetUserHwidDevices(ctx, HwidUserDevicesGetUserHwidDevicesParams{
		UserId: userid,
	}, options...)
}

// InfraBillingClient provides InfraBilling operations.
type InfraBillingClient struct {
	client *Client
}

// NewInfraBillingClient creates a new InfraBillingClient.
func NewInfraBillingClient(client *Client) *InfraBillingClient {
	return &InfraBillingClient{client: client}
}

// CreateInfraBillingNode calls InfraBilling_createInfraBillingNode.
func (sc *InfraBillingClient) CreateInfraBillingNode(ctx context.Context, request *CreateInfraBillingNodeBody, options ...RequestOption) (InfraBillingCreateInfraBillingNodeRes, error) {
	return sc.client.InfraBillingCreateInfraBillingNode(ctx, request, options...)
}

// CreateInfraBillingRecord calls InfraBilling_createInfraBillingRecord.
func (sc *InfraBillingClient) CreateInfraBillingRecord(ctx context.Context, request *CreateInfraBillingRecordBody, options ...RequestOption) (InfraBillingCreateInfraBillingRecordRes, error) {
	return sc.client.InfraBillingCreateInfraBillingRecord(ctx, request, options...)
}

// CreateInfraProvider calls InfraBilling_createInfraProvider.
func (sc *InfraBillingClient) CreateInfraProvider(ctx context.Context, request *CreateInfraProviderBody, options ...RequestOption) (InfraBillingCreateInfraProviderRes, error) {
	return sc.client.InfraBillingCreateInfraProvider(ctx, request, options...)
}

// DeleteInfraBillingNode calls InfraBilling_deleteInfraBillingNode.
func (sc *InfraBillingClient) DeleteInfraBillingNode(ctx context.Context, uuidValue string, options ...RequestOption) (InfraBillingDeleteInfraBillingNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InfraBillingDeleteInfraBillingNodeRes
		return zero0, err
	}

	return sc.client.InfraBillingDeleteInfraBillingNode(ctx, InfraBillingDeleteInfraBillingNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// DeleteInfraBillingRecord calls InfraBilling_deleteInfraBillingRecord.
func (sc *InfraBillingClient) DeleteInfraBillingRecord(ctx context.Context, uuidValue string, options ...RequestOption) (InfraBillingDeleteInfraBillingRecordRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InfraBillingDeleteInfraBillingRecordRes
		return zero0, err
	}

	return sc.client.InfraBillingDeleteInfraBillingRecord(ctx, InfraBillingDeleteInfraBillingRecordParams{
		UUID: parsedUUID,
	}, options...)
}

// DelteInfraProvider calls InfraBilling_delteInfraProvider.
func (sc *InfraBillingClient) DelteInfraProvider(ctx context.Context, uuidValue string, options ...RequestOption) (InfraBillingDelteInfraProviderRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InfraBillingDelteInfraProviderRes
		return zero0, err
	}

	return sc.client.InfraBillingDelteInfraProvider(ctx, InfraBillingDelteInfraProviderParams{
		UUID: parsedUUID,
	}, options...)
}

// GetBillingNodes calls InfraBilling_getBillingNodes.
func (sc *InfraBillingClient) GetBillingNodes(ctx context.Context, options ...RequestOption) (InfraBillingGetBillingNodesRes, error) {
	return sc.client.InfraBillingGetBillingNodes(ctx, options...)
}

// GetInfraBillingRecords calls InfraBilling_getInfraBillingRecords.
func (sc *InfraBillingClient) GetInfraBillingRecords(ctx context.Context, params InfraBillingGetInfraBillingRecordsParams, options ...RequestOption) (InfraBillingGetInfraBillingRecordsRes, error) {
	return sc.client.InfraBillingGetInfraBillingRecords(ctx, params, options...)
}

// GetInfraProvider calls InfraBilling_getInfraProvider.
func (sc *InfraBillingClient) GetInfraProvider(ctx context.Context, uuidValue string, options ...RequestOption) (InfraBillingGetInfraProviderRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InfraBillingGetInfraProviderRes
		return zero0, err
	}

	return sc.client.InfraBillingGetInfraProvider(ctx, InfraBillingGetInfraProviderParams{
		UUID: parsedUUID,
	}, options...)
}

// GetInfraProviders calls InfraBilling_getInfraProviders.
func (sc *InfraBillingClient) GetInfraProviders(ctx context.Context, options ...RequestOption) (InfraBillingGetInfraProvidersRes, error) {
	return sc.client.InfraBillingGetInfraProviders(ctx, options...)
}

// UpdateInfraBillingNode calls InfraBilling_updateInfraBillingNode.
func (sc *InfraBillingClient) UpdateInfraBillingNode(ctx context.Context, request *UpdateInfraBillingNodeBody, options ...RequestOption) (InfraBillingUpdateInfraBillingNodeRes, error) {
	return sc.client.InfraBillingUpdateInfraBillingNode(ctx, request, options...)
}

// UpdateInfraProvider calls InfraBilling_updateInfraProvider.
func (sc *InfraBillingClient) UpdateInfraProvider(ctx context.Context, request *UpdateInfraProviderBody, options ...RequestOption) (InfraBillingUpdateInfraProviderRes, error) {
	return sc.client.InfraBillingUpdateInfraProvider(ctx, request, options...)
}

// InternalSquadClient provides InternalSquad operations.
type InternalSquadClient struct {
	client *Client
}

// NewInternalSquadClient creates a new InternalSquadClient.
func NewInternalSquadClient(client *Client) *InternalSquadClient {
	return &InternalSquadClient{client: client}
}

// AddManyUsersToInternalSquad calls InternalSquad_addManyUsersToInternalSquad.
func (sc *InternalSquadClient) AddManyUsersToInternalSquad(ctx context.Context, request *InternalSquadBodyRequest, uuidValue string, options ...RequestOption) (InternalSquadAddManyUsersToInternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadAddManyUsersToInternalSquadRes
		return zero0, err
	}

	return sc.client.InternalSquadAddManyUsersToInternalSquad(ctx, request, InternalSquadAddManyUsersToInternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// AddUsersToInternalSquad calls InternalSquad_addUsersToInternalSquad.
func (sc *InternalSquadClient) AddUsersToInternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (InternalSquadAddUsersToInternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadAddUsersToInternalSquadRes
		return zero0, err
	}

	return sc.client.InternalSquadAddUsersToInternalSquad(ctx, InternalSquadAddUsersToInternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// CreateInternalSquad calls InternalSquad_createInternalSquad.
func (sc *InternalSquadClient) CreateInternalSquad(ctx context.Context, request *CreateInternalSquadBody, options ...RequestOption) (InternalSquadCreateInternalSquadRes, error) {
	return sc.client.InternalSquadCreateInternalSquad(ctx, request, options...)
}

// DeleteInternalSquad calls InternalSquad_deleteInternalSquad.
func (sc *InternalSquadClient) DeleteInternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (InternalSquadDeleteInternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadDeleteInternalSquadRes
		return zero0, err
	}

	return sc.client.InternalSquadDeleteInternalSquad(ctx, InternalSquadDeleteInternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// GetInternalSquadAccessibleNodes calls InternalSquad_getInternalSquadAccessibleNodes.
func (sc *InternalSquadClient) GetInternalSquadAccessibleNodes(ctx context.Context, uuidValue string, options ...RequestOption) (InternalSquadGetInternalSquadAccessibleNodesRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadGetInternalSquadAccessibleNodesRes
		return zero0, err
	}

	return sc.client.InternalSquadGetInternalSquadAccessibleNodes(ctx, InternalSquadGetInternalSquadAccessibleNodesParams{
		UUID: parsedUUID,
	}, options...)
}

// GetInternalSquadByUuid calls InternalSquad_getInternalSquadByUuid.
func (sc *InternalSquadClient) GetInternalSquadByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (InternalSquadGetInternalSquadByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadGetInternalSquadByUuidRes
		return zero0, err
	}

	return sc.client.InternalSquadGetInternalSquadByUuid(ctx, InternalSquadGetInternalSquadByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetInternalSquadUsage calls InternalSquad_getInternalSquadUsage.
func (sc *InternalSquadClient) GetInternalSquadUsage(ctx context.Context, params InternalSquadGetInternalSquadUsageParams, options ...RequestOption) (InternalSquadGetInternalSquadUsageRes, error) {
	return sc.client.InternalSquadGetInternalSquadUsage(ctx, params, options...)
}

// GetInternalSquads calls InternalSquad_getInternalSquads.
func (sc *InternalSquadClient) GetInternalSquads(ctx context.Context, options ...RequestOption) (InternalSquadGetInternalSquadsRes, error) {
	return sc.client.InternalSquadGetInternalSquads(ctx, options...)
}

// GetTags calls InternalSquad_getTags.
func (sc *InternalSquadClient) GetTags(ctx context.Context, options ...RequestOption) (InternalSquadGetTagsRes, error) {
	return sc.client.InternalSquadGetTags(ctx, options...)
}

// RemoveManyUsersFromInternalSquad calls InternalSquad_removeManyUsersFromInternalSquad.
func (sc *InternalSquadClient) RemoveManyUsersFromInternalSquad(ctx context.Context, request *InternalSquadBodyRequest, uuidValue string, options ...RequestOption) (InternalSquadRemoveManyUsersFromInternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadRemoveManyUsersFromInternalSquadRes
		return zero0, err
	}

	return sc.client.InternalSquadRemoveManyUsersFromInternalSquad(ctx, request, InternalSquadRemoveManyUsersFromInternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// RemoveUsersFromInternalSquad calls InternalSquad_removeUsersFromInternalSquad.
func (sc *InternalSquadClient) RemoveUsersFromInternalSquad(ctx context.Context, uuidValue string, options ...RequestOption) (InternalSquadRemoveUsersFromInternalSquadRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 InternalSquadRemoveUsersFromInternalSquadRes
		return zero0, err
	}

	return sc.client.InternalSquadRemoveUsersFromInternalSquad(ctx, InternalSquadRemoveUsersFromInternalSquadParams{
		UUID: parsedUUID,
	}, options...)
}

// ReorderInternalSquads calls InternalSquad_reorderInternalSquads.
func (sc *InternalSquadClient) ReorderInternalSquads(ctx context.Context, request *ReorderInternalSquadsBody, options ...RequestOption) (InternalSquadReorderInternalSquadsRes, error) {
	return sc.client.InternalSquadReorderInternalSquads(ctx, request, options...)
}

// SetTags calls InternalSquad_setTags.
func (sc *InternalSquadClient) SetTags(ctx context.Context, request *SetInternalSquadsTagsBody, options ...RequestOption) (InternalSquadSetTagsRes, error) {
	return sc.client.InternalSquadSetTags(ctx, request, options...)
}

// UpdateInternalSquad calls InternalSquad_updateInternalSquad.
func (sc *InternalSquadClient) UpdateInternalSquad(ctx context.Context, request *UpdateInternalSquadBody, options ...RequestOption) (InternalSquadUpdateInternalSquadRes, error) {
	return sc.client.InternalSquadUpdateInternalSquad(ctx, request, options...)
}

// InternalSquadStatsClient provides InternalSquadStats operations.
type InternalSquadStatsClient struct {
	client *Client
}

// NewInternalSquadStatsClient creates a new InternalSquadStatsClient.
func NewInternalSquadStatsClient(client *Client) *InternalSquadStatsClient {
	return &InternalSquadStatsClient{client: client}
}

// GetInternalSquadUsage calls InternalSquadStats_getInternalSquadUsage.
func (sc *InternalSquadStatsClient) GetInternalSquadUsage(ctx context.Context, params InternalSquadStatsGetInternalSquadUsageParams, options ...RequestOption) (InternalSquadStatsGetInternalSquadUsageRes, error) {
	return sc.client.InternalSquadStatsGetInternalSquadUsage(ctx, params, options...)
}

// GetInternalSquadUserUsage calls InternalSquadStats_getInternalSquadUserUsage.
func (sc *InternalSquadStatsClient) GetInternalSquadUserUsage(ctx context.Context, params InternalSquadStatsGetInternalSquadUserUsageParams, options ...RequestOption) (InternalSquadStatsGetInternalSquadUserUsageRes, error) {
	return sc.client.InternalSquadStatsGetInternalSquadUserUsage(ctx, params, options...)
}

// KeygenClient provides Keygen operations.
type KeygenClient struct {
	client *Client
}

// NewKeygenClient creates a new KeygenClient.
func NewKeygenClient(client *Client) *KeygenClient {
	return &KeygenClient{client: client}
}

// GenerateKey calls Keygen_generateKey.
func (sc *KeygenClient) GenerateKey(ctx context.Context, options ...RequestOption) (KeygenGenerateKeyRes, error) {
	return sc.client.KeygenGenerateKey(ctx, options...)
}

// MetadataClient provides Metadata operations.
type MetadataClient struct {
	client *Client
}

// NewMetadataClient creates a new MetadataClient.
func NewMetadataClient(client *Client) *MetadataClient {
	return &MetadataClient{client: client}
}

// GetNodeMetadata calls Metadata_getNodeMetadata.
func (sc *MetadataClient) GetNodeMetadata(ctx context.Context, uuidValue string, options ...RequestOption) (MetadataGetNodeMetadataRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 MetadataGetNodeMetadataRes
		return zero0, err
	}

	return sc.client.MetadataGetNodeMetadata(ctx, MetadataGetNodeMetadataParams{
		UUID: parsedUUID,
	}, options...)
}

// GetUserMetadata calls Metadata_getUserMetadata.
func (sc *MetadataClient) GetUserMetadata(ctx context.Context, userid int, options ...RequestOption) (MetadataGetUserMetadataRes, error) {

	return sc.client.MetadataGetUserMetadata(ctx, MetadataGetUserMetadataParams{
		UserId: userid,
	}, options...)
}

// UpsertNodeMetadata calls Metadata_upsertNodeMetadata.
func (sc *MetadataClient) UpsertNodeMetadata(ctx context.Context, request *UpsertNodeMetadataBody, uuidValue string, options ...RequestOption) (MetadataUpsertNodeMetadataRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 MetadataUpsertNodeMetadataRes
		return zero0, err
	}

	return sc.client.MetadataUpsertNodeMetadata(ctx, request, MetadataUpsertNodeMetadataParams{
		UUID: parsedUUID,
	}, options...)
}

// UpsertUserMetadata calls Metadata_upsertUserMetadata.
func (sc *MetadataClient) UpsertUserMetadata(ctx context.Context, request *UpsertUserMetadataBody, userid int, options ...RequestOption) (MetadataUpsertUserMetadataRes, error) {

	return sc.client.MetadataUpsertUserMetadata(ctx, request, MetadataUpsertUserMetadataParams{
		UserId: userid,
	}, options...)
}

// NodeIntegrationClient provides NodeIntegration operations.
type NodeIntegrationClient struct {
	client *Client
}

// NewNodeIntegrationClient creates a new NodeIntegrationClient.
func NewNodeIntegrationClient(client *Client) *NodeIntegrationClient {
	return &NodeIntegrationClient{client: client}
}

// CreateIntegration calls NodeIntegration_createIntegration.
func (sc *NodeIntegrationClient) CreateIntegration(ctx context.Context, request *CreateNodeIntegrationBody, options ...RequestOption) (NodeIntegrationCreateIntegrationRes, error) {
	return sc.client.NodeIntegrationCreateIntegration(ctx, request, options...)
}

// DeleteIntegration calls NodeIntegration_deleteIntegration.
func (sc *NodeIntegrationClient) DeleteIntegration(ctx context.Context, uuidValue string, options ...RequestOption) (NodeIntegrationDeleteIntegrationRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodeIntegrationDeleteIntegrationRes
		return zero0, err
	}

	return sc.client.NodeIntegrationDeleteIntegration(ctx, NodeIntegrationDeleteIntegrationParams{
		UUID: parsedUUID,
	}, options...)
}

// GetAllIntegrations calls NodeIntegration_getAllIntegrations.
func (sc *NodeIntegrationClient) GetAllIntegrations(ctx context.Context, options ...RequestOption) (NodeIntegrationGetAllIntegrationsRes, error) {
	return sc.client.NodeIntegrationGetAllIntegrations(ctx, options...)
}

// GetIntegrationByUuid calls NodeIntegration_getIntegrationByUuid.
func (sc *NodeIntegrationClient) GetIntegrationByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (NodeIntegrationGetIntegrationByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodeIntegrationGetIntegrationByUuidRes
		return zero0, err
	}

	return sc.client.NodeIntegrationGetIntegrationByUuid(ctx, NodeIntegrationGetIntegrationByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// UpdateIntegration calls NodeIntegration_updateIntegration.
func (sc *NodeIntegrationClient) UpdateIntegration(ctx context.Context, request *UpdateNodeIntegrationBody, options ...RequestOption) (NodeIntegrationUpdateIntegrationRes, error) {
	return sc.client.NodeIntegrationUpdateIntegration(ctx, request, options...)
}

// NodePluginClient provides NodePlugin operations.
type NodePluginClient struct {
	client *Client
}

// NewNodePluginClient creates a new NodePluginClient.
func NewNodePluginClient(client *Client) *NodePluginClient {
	return &NodePluginClient{client: client}
}

// CloneNodePlugin calls NodePlugin_cloneNodePlugin.
func (sc *NodePluginClient) CloneNodePlugin(ctx context.Context, request *CloneNodePluginBody, options ...RequestOption) (NodePluginCloneNodePluginRes, error) {
	return sc.client.NodePluginCloneNodePlugin(ctx, request, options...)
}

// CreateConfig calls NodePlugin_createConfig.
func (sc *NodePluginClient) CreateConfig(ctx context.Context, request *CreateNodePluginBody, options ...RequestOption) (NodePluginCreateConfigRes, error) {
	return sc.client.NodePluginCreateConfig(ctx, request, options...)
}

// CreateSharedList calls NodePlugin_createSharedList.
func (sc *NodePluginClient) CreateSharedList(ctx context.Context, request *SharedListBodyBulkRequest, options ...RequestOption) (NodePluginCreateSharedListRes, error) {
	return sc.client.NodePluginCreateSharedList(ctx, request, options...)
}

// DeleteConfig calls NodePlugin_deleteConfig.
func (sc *NodePluginClient) DeleteConfig(ctx context.Context, uuidValue string, options ...RequestOption) (NodePluginDeleteConfigRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodePluginDeleteConfigRes
		return zero0, err
	}

	return sc.client.NodePluginDeleteConfig(ctx, NodePluginDeleteConfigParams{
		UUID: parsedUUID,
	}, options...)
}

// DeleteSharedList calls NodePlugin_deleteSharedList.
func (sc *NodePluginClient) DeleteSharedList(ctx context.Context, request *SharedListBodyBulkRequest2, options ...RequestOption) (NodePluginDeleteSharedListRes, error) {
	return sc.client.NodePluginDeleteSharedList(ctx, request, options...)
}

// GetAllConfigs calls NodePlugin_getAllConfigs.
func (sc *NodePluginClient) GetAllConfigs(ctx context.Context, options ...RequestOption) (NodePluginGetAllConfigsRes, error) {
	return sc.client.NodePluginGetAllConfigs(ctx, options...)
}

// GetAllSharedLists calls NodePlugin_getAllSharedLists.
func (sc *NodePluginClient) GetAllSharedLists(ctx context.Context, options ...RequestOption) (NodePluginGetAllSharedListsRes, error) {
	return sc.client.NodePluginGetAllSharedLists(ctx, options...)
}

// GetConfigByUuid calls NodePlugin_getConfigByUuid.
func (sc *NodePluginClient) GetConfigByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (NodePluginGetConfigByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodePluginGetConfigByUuidRes
		return zero0, err
	}

	return sc.client.NodePluginGetConfigByUuid(ctx, NodePluginGetConfigByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetSharedListByName calls NodePlugin_getSharedListByName.
func (sc *NodePluginClient) GetSharedListByName(ctx context.Context, name string, options ...RequestOption) (NodePluginGetSharedListByNameRes, error) {

	return sc.client.NodePluginGetSharedListByName(ctx, NodePluginGetSharedListByNameParams{
		Name: name,
	}, options...)
}

// GetTags calls NodePlugin_getTags.
func (sc *NodePluginClient) GetTags(ctx context.Context, options ...RequestOption) (NodePluginGetTagsRes, error) {
	return sc.client.NodePluginGetTags(ctx, options...)
}

// PluginExecutor calls NodePlugin_pluginExecutor.
func (sc *NodePluginClient) PluginExecutor(ctx context.Context, request *PluginExecutorBody, options ...RequestOption) (NodePluginPluginExecutorRes, error) {
	return sc.client.NodePluginPluginExecutor(ctx, request, options...)
}

// ReorderNodePlugins calls NodePlugin_reorderNodePlugins.
func (sc *NodePluginClient) ReorderNodePlugins(ctx context.Context, request *ReorderNodePluginsBody, options ...RequestOption) (NodePluginReorderNodePluginsRes, error) {
	return sc.client.NodePluginReorderNodePlugins(ctx, request, options...)
}

// SetTags calls NodePlugin_setTags.
func (sc *NodePluginClient) SetTags(ctx context.Context, request *SetNodePluginsTagsBody, options ...RequestOption) (NodePluginSetTagsRes, error) {
	return sc.client.NodePluginSetTags(ctx, request, options...)
}

// SyncNodePlugin calls NodePlugin_syncNodePlugin.
func (sc *NodePluginClient) SyncNodePlugin(ctx context.Context, request *SyncNodePluginBody, options ...RequestOption) (NodePluginSyncNodePluginRes, error) {
	return sc.client.NodePluginSyncNodePlugin(ctx, request, options...)
}

// SyncSharedList calls NodePlugin_syncSharedList.
func (sc *NodePluginClient) SyncSharedList(ctx context.Context, request *SharedListBodyBulkRequest2, options ...RequestOption) (NodePluginSyncSharedListRes, error) {
	return sc.client.NodePluginSyncSharedList(ctx, request, options...)
}

// UpdateConfig calls NodePlugin_updateConfig.
func (sc *NodePluginClient) UpdateConfig(ctx context.Context, request *UpdateNodePluginBody, options ...RequestOption) (NodePluginUpdateConfigRes, error) {
	return sc.client.NodePluginUpdateConfig(ctx, request, options...)
}

// UpdateSharedList calls NodePlugin_updateSharedList.
func (sc *NodePluginClient) UpdateSharedList(ctx context.Context, request *SharedListBodyBulkRequest, options ...RequestOption) (NodePluginUpdateSharedListRes, error) {
	return sc.client.NodePluginUpdateSharedList(ctx, request, options...)
}

// NodesClient provides Nodes operations.
type NodesClient struct {
	client *Client
}

// NewNodesClient creates a new NodesClient.
func NewNodesClient(client *Client) *NodesClient {
	return &NodesClient{client: client}
}

// BulkNodesActions calls Nodes_bulkNodesActions.
func (sc *NodesClient) BulkNodesActions(ctx context.Context, request *BulkNodesActionsBody, options ...RequestOption) (NodesBulkNodesActionsRes, error) {
	return sc.client.NodesBulkNodesActions(ctx, request, options...)
}

// BulkNodesUpdate calls Nodes_bulkNodesUpdate.
func (sc *NodesClient) BulkNodesUpdate(ctx context.Context, request *BulkNodesUpdateBody, options ...RequestOption) (NodesBulkNodesUpdateRes, error) {
	return sc.client.NodesBulkNodesUpdate(ctx, request, options...)
}

// CreateNode calls Nodes_createNode.
func (sc *NodesClient) CreateNode(ctx context.Context, request *CreateNodeBody, options ...RequestOption) (NodesCreateNodeRes, error) {
	return sc.client.NodesCreateNode(ctx, request, options...)
}

// DeleteNode calls Nodes_deleteNode.
func (sc *NodesClient) DeleteNode(ctx context.Context, uuidValue string, options ...RequestOption) (NodesDeleteNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesDeleteNodeRes
		return zero0, err
	}

	return sc.client.NodesDeleteNode(ctx, NodesDeleteNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// DisableNode calls Nodes_disableNode.
func (sc *NodesClient) DisableNode(ctx context.Context, uuidValue string, options ...RequestOption) (NodesDisableNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesDisableNodeRes
		return zero0, err
	}

	return sc.client.NodesDisableNode(ctx, NodesDisableNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// EnableNode calls Nodes_enableNode.
func (sc *NodesClient) EnableNode(ctx context.Context, uuidValue string, options ...RequestOption) (NodesEnableNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesEnableNodeRes
		return zero0, err
	}

	return sc.client.NodesEnableNode(ctx, NodesEnableNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// GetNode calls Nodes_getNode.
func (sc *NodesClient) GetNode(ctx context.Context, uuidValue string, options ...RequestOption) (NodesGetNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesGetNodeRes
		return zero0, err
	}

	return sc.client.NodesGetNode(ctx, NodesGetNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// GetNodes calls Nodes_getNodes.
func (sc *NodesClient) GetNodes(ctx context.Context, options ...RequestOption) (NodesGetNodesRes, error) {
	return sc.client.NodesGetNodes(ctx, options...)
}

// GetNodesTags calls Nodes_getNodesTags.
func (sc *NodesClient) GetNodesTags(ctx context.Context, options ...RequestOption) (NodesGetNodesTagsRes, error) {
	return sc.client.NodesGetNodesTags(ctx, options...)
}

// ProfileModification calls Nodes_profileModification.
func (sc *NodesClient) ProfileModification(ctx context.Context, request *ProfileModificationBody, options ...RequestOption) (NodesProfileModificationRes, error) {
	return sc.client.NodesProfileModification(ctx, request, options...)
}

// ReorderNodes calls Nodes_reorderNodes.
func (sc *NodesClient) ReorderNodes(ctx context.Context, request *ReorderNodesBody, options ...RequestOption) (NodesReorderNodesRes, error) {
	return sc.client.NodesReorderNodes(ctx, request, options...)
}

// ResetNodeTraffic calls Nodes_resetNodeTraffic.
func (sc *NodesClient) ResetNodeTraffic(ctx context.Context, uuidValue string, options ...RequestOption) (NodesResetNodeTrafficRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesResetNodeTrafficRes
		return zero0, err
	}

	return sc.client.NodesResetNodeTraffic(ctx, NodesResetNodeTrafficParams{
		UUID: parsedUUID,
	}, options...)
}

// RestartAllNodes calls Nodes_restartAllNodes.
func (sc *NodesClient) RestartAllNodes(ctx context.Context, request *NodeBodyRequest, options ...RequestOption) (NodesRestartAllNodesRes, error) {
	return sc.client.NodesRestartAllNodes(ctx, request, options...)
}

// RestartNode calls Nodes_restartNode.
func (sc *NodesClient) RestartNode(ctx context.Context, request *NodeBodyRequest, uuidValue string, options ...RequestOption) (NodesRestartNodeRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 NodesRestartNodeRes
		return zero0, err
	}

	return sc.client.NodesRestartNode(ctx, request, NodesRestartNodeParams{
		UUID: parsedUUID,
	}, options...)
}

// UpdateNode calls Nodes_updateNode.
func (sc *NodesClient) UpdateNode(ctx context.Context, request *UpdateNodeBody, options ...RequestOption) (NodesUpdateNodeRes, error) {
	return sc.client.NodesUpdateNode(ctx, request, options...)
}

// NodesUsageHistoryClient provides NodesUsageHistory operations.
type NodesUsageHistoryClient struct {
	client *Client
}

// NewNodesUsageHistoryClient creates a new NodesUsageHistoryClient.
func NewNodesUsageHistoryClient(client *Client) *NodesUsageHistoryClient {
	return &NodesUsageHistoryClient{client: client}
}

// GetStatsNodesUsage calls NodesUsageHistory_getStatsNodesUsage.
func (sc *NodesUsageHistoryClient) GetStatsNodesUsage(ctx context.Context, params NodesUsageHistoryGetStatsNodesUsageParams, options ...RequestOption) (NodesUsageHistoryGetStatsNodesUsageRes, error) {
	return sc.client.NodesUsageHistoryGetStatsNodesUsage(ctx, params, options...)
}

// PasskeyClient provides Passkey operations.
type PasskeyClient struct {
	client *Client
}

// NewPasskeyClient creates a new PasskeyClient.
func NewPasskeyClient(client *Client) *PasskeyClient {
	return &PasskeyClient{client: client}
}

// DeletePasskey calls Passkey_deletePasskey.
func (sc *PasskeyClient) DeletePasskey(ctx context.Context, request *DeletePasskeyBody, options ...RequestOption) (PasskeyDeletePasskeyRes, error) {
	return sc.client.PasskeyDeletePasskey(ctx, request, options...)
}

// GetActivePasskeys calls Passkey_getActivePasskeys.
func (sc *PasskeyClient) GetActivePasskeys(ctx context.Context, options ...RequestOption) (PasskeyGetActivePasskeysRes, error) {
	return sc.client.PasskeyGetActivePasskeys(ctx, options...)
}

// PasskeyRegistrationOptions calls Passkey_passkeyRegistrationOptions.
func (sc *PasskeyClient) PasskeyRegistrationOptions(ctx context.Context, options ...RequestOption) (PasskeyPasskeyRegistrationOptionsRes, error) {
	return sc.client.PasskeyPasskeyRegistrationOptions(ctx, options...)
}

// PasskeyRegistrationVerify calls Passkey_passkeyRegistrationVerify.
func (sc *PasskeyClient) PasskeyRegistrationVerify(ctx context.Context, request *PasskeyOptions, options ...RequestOption) (PasskeyPasskeyRegistrationVerifyRes, error) {
	return sc.client.PasskeyPasskeyRegistrationVerify(ctx, request, options...)
}

// UpdatePasskey calls Passkey_updatePasskey.
func (sc *PasskeyClient) UpdatePasskey(ctx context.Context, request *UpdatePasskeyBody, options ...RequestOption) (PasskeyUpdatePasskeyRes, error) {
	return sc.client.PasskeyUpdatePasskey(ctx, request, options...)
}

// RemnawaveSettingsClient provides RemnawaveSettings operations.
type RemnawaveSettingsClient struct {
	client *Client
}

// NewRemnawaveSettingsClient creates a new RemnawaveSettingsClient.
func NewRemnawaveSettingsClient(client *Client) *RemnawaveSettingsClient {
	return &RemnawaveSettingsClient{client: client}
}

// GetSettings calls RemnawaveSettings_getSettings.
func (sc *RemnawaveSettingsClient) GetSettings(ctx context.Context, options ...RequestOption) (RemnawaveSettingsGetSettingsRes, error) {
	return sc.client.RemnawaveSettingsGetSettings(ctx, options...)
}

// UpdateSettings calls RemnawaveSettings_updateSettings.
func (sc *RemnawaveSettingsClient) UpdateSettings(ctx context.Context, request *UpdateRemnawaveSettingsBody, options ...RequestOption) (RemnawaveSettingsUpdateSettingsRes, error) {
	return sc.client.RemnawaveSettingsUpdateSettings(ctx, request, options...)
}

// SnippetsClient provides Snippets operations.
type SnippetsClient struct {
	client *Client
}

// NewSnippetsClient creates a new SnippetsClient.
func NewSnippetsClient(client *Client) *SnippetsClient {
	return &SnippetsClient{client: client}
}

// CreateSnippet calls Snippets_createSnippet.
func (sc *SnippetsClient) CreateSnippet(ctx context.Context, request *SnippetBodyRequest2, options ...RequestOption) (SnippetsCreateSnippetRes, error) {
	return sc.client.SnippetsCreateSnippet(ctx, request, options...)
}

// DeleteSnippetByName calls Snippets_deleteSnippetByName.
func (sc *SnippetsClient) DeleteSnippetByName(ctx context.Context, request *SnippetBodyRequest, options ...RequestOption) (SnippetsDeleteSnippetByNameRes, error) {
	return sc.client.SnippetsDeleteSnippetByName(ctx, request, options...)
}

// GetSnippets calls Snippets_getSnippets.
func (sc *SnippetsClient) GetSnippets(ctx context.Context, options ...RequestOption) (SnippetsGetSnippetsRes, error) {
	return sc.client.SnippetsGetSnippets(ctx, options...)
}

// SyncSnippet calls Snippets_syncSnippet.
func (sc *SnippetsClient) SyncSnippet(ctx context.Context, request *SnippetBodyRequest, options ...RequestOption) (SnippetsSyncSnippetRes, error) {
	return sc.client.SnippetsSyncSnippet(ctx, request, options...)
}

// UpdateSnippet calls Snippets_updateSnippet.
func (sc *SnippetsClient) UpdateSnippet(ctx context.Context, request *SnippetBodyRequest2, options ...RequestOption) (SnippetsUpdateSnippetRes, error) {
	return sc.client.SnippetsUpdateSnippet(ctx, request, options...)
}

// SubscriptionClient provides Subscription operations.
type SubscriptionClient struct {
	client *Client
}

// NewSubscriptionClient creates a new SubscriptionClient.
func NewSubscriptionClient(client *Client) *SubscriptionClient {
	return &SubscriptionClient{client: client}
}

// GetSubscription calls Subscription_getSubscription.
func (sc *SubscriptionClient) GetSubscription(ctx context.Context, shortuuid string, options ...RequestOption) (SubscriptionGetSubscriptionRes, error) {

	return sc.client.SubscriptionGetSubscription(ctx, SubscriptionGetSubscriptionParams{
		ShortUuid: shortuuid,
	}, options...)
}

// GetSubscriptionByClientType calls Subscription_getSubscriptionByClientType.
func (sc *SubscriptionClient) GetSubscriptionByClientType(ctx context.Context, params SubscriptionGetSubscriptionByClientTypeParams, options ...RequestOption) (SubscriptionGetSubscriptionByClientTypeRes, error) {
	return sc.client.SubscriptionGetSubscriptionByClientType(ctx, params, options...)
}

// GetSubscriptionInfoByShortUuid calls Subscription_getSubscriptionInfoByShortUuid.
func (sc *SubscriptionClient) GetSubscriptionInfoByShortUuid(ctx context.Context, shortuuid string, options ...RequestOption) (SubscriptionGetSubscriptionInfoByShortUuidRes, error) {

	return sc.client.SubscriptionGetSubscriptionInfoByShortUuid(ctx, SubscriptionGetSubscriptionInfoByShortUuidParams{
		ShortUuid: shortuuid,
	}, options...)
}

// SubscriptionPageConfigClient provides SubscriptionPageConfig operations.
type SubscriptionPageConfigClient struct {
	client *Client
}

// NewSubscriptionPageConfigClient creates a new SubscriptionPageConfigClient.
func NewSubscriptionPageConfigClient(client *Client) *SubscriptionPageConfigClient {
	return &SubscriptionPageConfigClient{client: client}
}

// CloneSubscriptionPageConfig calls SubscriptionPageConfig_cloneSubscriptionPageConfig.
func (sc *SubscriptionPageConfigClient) CloneSubscriptionPageConfig(ctx context.Context, request *CloneSubpageConfigBody, options ...RequestOption) (SubscriptionPageConfigCloneSubscriptionPageConfigRes, error) {
	return sc.client.SubscriptionPageConfigCloneSubscriptionPageConfig(ctx, request, options...)
}

// CreateConfig calls SubscriptionPageConfig_createConfig.
func (sc *SubscriptionPageConfigClient) CreateConfig(ctx context.Context, request *CreateSubpageConfigBody, options ...RequestOption) (SubscriptionPageConfigCreateConfigRes, error) {
	return sc.client.SubscriptionPageConfigCreateConfig(ctx, request, options...)
}

// DeleteConfig calls SubscriptionPageConfig_deleteConfig.
func (sc *SubscriptionPageConfigClient) DeleteConfig(ctx context.Context, uuidValue string, options ...RequestOption) (SubscriptionPageConfigDeleteConfigRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 SubscriptionPageConfigDeleteConfigRes
		return zero0, err
	}

	return sc.client.SubscriptionPageConfigDeleteConfig(ctx, SubscriptionPageConfigDeleteConfigParams{
		UUID: parsedUUID,
	}, options...)
}

// GetAllConfigs calls SubscriptionPageConfig_getAllConfigs.
func (sc *SubscriptionPageConfigClient) GetAllConfigs(ctx context.Context, options ...RequestOption) (SubscriptionPageConfigGetAllConfigsRes, error) {
	return sc.client.SubscriptionPageConfigGetAllConfigs(ctx, options...)
}

// GetConfigByUuid calls SubscriptionPageConfig_getConfigByUuid.
func (sc *SubscriptionPageConfigClient) GetConfigByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (SubscriptionPageConfigGetConfigByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 SubscriptionPageConfigGetConfigByUuidRes
		return zero0, err
	}

	return sc.client.SubscriptionPageConfigGetConfigByUuid(ctx, SubscriptionPageConfigGetConfigByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// GetTags calls SubscriptionPageConfig_getTags.
func (sc *SubscriptionPageConfigClient) GetTags(ctx context.Context, options ...RequestOption) (SubscriptionPageConfigGetTagsRes, error) {
	return sc.client.SubscriptionPageConfigGetTags(ctx, options...)
}

// ReorderSubscriptionPageConfigs calls SubscriptionPageConfig_reorderSubscriptionPageConfigs.
func (sc *SubscriptionPageConfigClient) ReorderSubscriptionPageConfigs(ctx context.Context, request *ReorderSubpageConfigsBody, options ...RequestOption) (SubscriptionPageConfigReorderSubscriptionPageConfigsRes, error) {
	return sc.client.SubscriptionPageConfigReorderSubscriptionPageConfigs(ctx, request, options...)
}

// SetTags calls SubscriptionPageConfig_setTags.
func (sc *SubscriptionPageConfigClient) SetTags(ctx context.Context, request *SetSubpageConfigsTagsBody, options ...RequestOption) (SubscriptionPageConfigSetTagsRes, error) {
	return sc.client.SubscriptionPageConfigSetTags(ctx, request, options...)
}

// UpdateConfig calls SubscriptionPageConfig_updateConfig.
func (sc *SubscriptionPageConfigClient) UpdateConfig(ctx context.Context, request *UpdateSubpageConfigBody, options ...RequestOption) (SubscriptionPageConfigUpdateConfigRes, error) {
	return sc.client.SubscriptionPageConfigUpdateConfig(ctx, request, options...)
}

// SubscriptionSettingsClient provides SubscriptionSettings operations.
type SubscriptionSettingsClient struct {
	client *Client
}

// NewSubscriptionSettingsClient creates a new SubscriptionSettingsClient.
func NewSubscriptionSettingsClient(client *Client) *SubscriptionSettingsClient {
	return &SubscriptionSettingsClient{client: client}
}

// GetSettings calls SubscriptionSettings_getSettings.
func (sc *SubscriptionSettingsClient) GetSettings(ctx context.Context, options ...RequestOption) (SubscriptionSettingsGetSettingsRes, error) {
	return sc.client.SubscriptionSettingsGetSettings(ctx, options...)
}

// UpdateSettings calls SubscriptionSettings_updateSettings.
func (sc *SubscriptionSettingsClient) UpdateSettings(ctx context.Context, request *UpdateSubscriptionSettingsBody, options ...RequestOption) (SubscriptionSettingsUpdateSettingsRes, error) {
	return sc.client.SubscriptionSettingsUpdateSettings(ctx, request, options...)
}

// SubscriptionTemplateClient provides SubscriptionTemplate operations.
type SubscriptionTemplateClient struct {
	client *Client
}

// NewSubscriptionTemplateClient creates a new SubscriptionTemplateClient.
func NewSubscriptionTemplateClient(client *Client) *SubscriptionTemplateClient {
	return &SubscriptionTemplateClient{client: client}
}

// CreateTemplate calls SubscriptionTemplate_createTemplate.
func (sc *SubscriptionTemplateClient) CreateTemplate(ctx context.Context, request *CreateSubscriptionTemplateBody, options ...RequestOption) (SubscriptionTemplateCreateTemplateRes, error) {
	return sc.client.SubscriptionTemplateCreateTemplate(ctx, request, options...)
}

// DeleteTemplate calls SubscriptionTemplate_deleteTemplate.
func (sc *SubscriptionTemplateClient) DeleteTemplate(ctx context.Context, uuidValue string, options ...RequestOption) (SubscriptionTemplateDeleteTemplateRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 SubscriptionTemplateDeleteTemplateRes
		return zero0, err
	}

	return sc.client.SubscriptionTemplateDeleteTemplate(ctx, SubscriptionTemplateDeleteTemplateParams{
		UUID: parsedUUID,
	}, options...)
}

// GetAllTemplates calls SubscriptionTemplate_getAllTemplates.
func (sc *SubscriptionTemplateClient) GetAllTemplates(ctx context.Context, options ...RequestOption) (SubscriptionTemplateGetAllTemplatesRes, error) {
	return sc.client.SubscriptionTemplateGetAllTemplates(ctx, options...)
}

// GetTags calls SubscriptionTemplate_getTags.
func (sc *SubscriptionTemplateClient) GetTags(ctx context.Context, options ...RequestOption) (SubscriptionTemplateGetTagsRes, error) {
	return sc.client.SubscriptionTemplateGetTags(ctx, options...)
}

// GetTemplateByUuid calls SubscriptionTemplate_getTemplateByUuid.
func (sc *SubscriptionTemplateClient) GetTemplateByUuid(ctx context.Context, uuidValue string, options ...RequestOption) (SubscriptionTemplateGetTemplateByUuidRes, error) {
	parsedUUID, err := uuid.Parse(uuidValue)
	if err != nil {
		var zero0 SubscriptionTemplateGetTemplateByUuidRes
		return zero0, err
	}

	return sc.client.SubscriptionTemplateGetTemplateByUuid(ctx, SubscriptionTemplateGetTemplateByUuidParams{
		UUID: parsedUUID,
	}, options...)
}

// ReorderSubscriptionTemplates calls SubscriptionTemplate_reorderSubscriptionTemplates.
func (sc *SubscriptionTemplateClient) ReorderSubscriptionTemplates(ctx context.Context, request *ReorderSubscriptionTemplatesBody, options ...RequestOption) (SubscriptionTemplateReorderSubscriptionTemplatesRes, error) {
	return sc.client.SubscriptionTemplateReorderSubscriptionTemplates(ctx, request, options...)
}

// SetTags calls SubscriptionTemplate_setTags.
func (sc *SubscriptionTemplateClient) SetTags(ctx context.Context, request *SetSubscriptionTemplatesTagsBody, options ...RequestOption) (SubscriptionTemplateSetTagsRes, error) {
	return sc.client.SubscriptionTemplateSetTags(ctx, request, options...)
}

// UpdateTemplate calls SubscriptionTemplate_updateTemplate.
func (sc *SubscriptionTemplateClient) UpdateTemplate(ctx context.Context, request *UpdateTemplateBody, options ...RequestOption) (SubscriptionTemplateUpdateTemplateRes, error) {
	return sc.client.SubscriptionTemplateUpdateTemplate(ctx, request, options...)
}

// SubscriptionsClient provides Subscriptions operations.
type SubscriptionsClient struct {
	client *Client
}

// NewSubscriptionsClient creates a new SubscriptionsClient.
func NewSubscriptionsClient(client *Client) *SubscriptionsClient {
	return &SubscriptionsClient{client: client}
}

// GetAllSubscriptions calls Subscriptions_getAllSubscriptions.
func (sc *SubscriptionsClient) GetAllSubscriptions(ctx context.Context, params SubscriptionsGetAllSubscriptionsParams, options ...RequestOption) (SubscriptionsGetAllSubscriptionsRes, error) {
	return sc.client.SubscriptionsGetAllSubscriptions(ctx, params, options...)
}

// GetConnectionKeysByUserId calls Subscriptions_getConnectionKeysByUserId.
func (sc *SubscriptionsClient) GetConnectionKeysByUserId(ctx context.Context, userid int, options ...RequestOption) (SubscriptionsGetConnectionKeysByUserIdRes, error) {

	return sc.client.SubscriptionsGetConnectionKeysByUserId(ctx, SubscriptionsGetConnectionKeysByUserIdParams{
		UserId: userid,
	}, options...)
}

// GetRawSubscriptionByShortUuid calls Subscriptions_getRawSubscriptionByShortUuid.
func (sc *SubscriptionsClient) GetRawSubscriptionByShortUuid(ctx context.Context, params SubscriptionsGetRawSubscriptionByShortUuidParams, options ...RequestOption) (SubscriptionsGetRawSubscriptionByShortUuidRes, error) {
	return sc.client.SubscriptionsGetRawSubscriptionByShortUuid(ctx, params, options...)
}

// GetSubpageConfigByShortUuid calls Subscriptions_getSubpageConfigByShortUuid.
func (sc *SubscriptionsClient) GetSubpageConfigByShortUuid(ctx context.Context, request *GetSubpageConfigByShortUuidBody, shortuuid string, options ...RequestOption) (SubscriptionsGetSubpageConfigByShortUuidRes, error) {

	return sc.client.SubscriptionsGetSubpageConfigByShortUuid(ctx, request, SubscriptionsGetSubpageConfigByShortUuidParams{
		ShortUuid: shortuuid,
	}, options...)
}

// GetSubscriptionByShortUuidProtected calls Subscriptions_getSubscriptionByShortUuidProtected.
func (sc *SubscriptionsClient) GetSubscriptionByShortUuidProtected(ctx context.Context, shortuuid string, options ...RequestOption) (SubscriptionsGetSubscriptionByShortUuidProtectedRes, error) {

	return sc.client.SubscriptionsGetSubscriptionByShortUuidProtected(ctx, SubscriptionsGetSubscriptionByShortUuidProtectedParams{
		ShortUuid: shortuuid,
	}, options...)
}

// GetSubscriptionByUsername calls Subscriptions_getSubscriptionByUsername.
func (sc *SubscriptionsClient) GetSubscriptionByUsername(ctx context.Context, username string, options ...RequestOption) (SubscriptionsGetSubscriptionByUsernameRes, error) {

	return sc.client.SubscriptionsGetSubscriptionByUsername(ctx, SubscriptionsGetSubscriptionByUsernameParams{
		Username: username,
	}, options...)
}

// GetSubscriptionByUuid calls Subscriptions_getSubscriptionByUuid.
func (sc *SubscriptionsClient) GetSubscriptionByUuid(ctx context.Context, userid int, options ...RequestOption) (SubscriptionsGetSubscriptionByUuidRes, error) {

	return sc.client.SubscriptionsGetSubscriptionByUuid(ctx, SubscriptionsGetSubscriptionByUuidParams{
		UserId: userid,
	}, options...)
}

// SystemClient provides System operations.
type SystemClient struct {
	client *Client
}

// NewSystemClient creates a new SystemClient.
func NewSystemClient(client *Client) *SystemClient {
	return &SystemClient{client: client}
}

// DebugSrrMatcher calls System_debugSrrMatcher.
func (sc *SystemClient) DebugSrrMatcher(ctx context.Context, request *DebugSrrMatcherBody, options ...RequestOption) (SystemDebugSrrMatcherRes, error) {
	return sc.client.SystemDebugSrrMatcher(ctx, request, options...)
}

// GetBandwidthStats calls System_getBandwidthStats.
func (sc *SystemClient) GetBandwidthStats(ctx context.Context, params SystemGetBandwidthStatsParams, options ...RequestOption) (SystemGetBandwidthStatsRes, error) {
	return sc.client.SystemGetBandwidthStats(ctx, params, options...)
}

// GetConfiguration calls System_getConfiguration.
func (sc *SystemClient) GetConfiguration(ctx context.Context, options ...RequestOption) (SystemGetConfigurationRes, error) {
	return sc.client.SystemGetConfiguration(ctx, options...)
}

// GetHttpStats calls System_getHttpStats.
func (sc *SystemClient) GetHttpStats(ctx context.Context, options ...RequestOption) (SystemGetHttpStatsRes, error) {
	return sc.client.SystemGetHttpStats(ctx, options...)
}

// GetMetadata calls System_getMetadata.
func (sc *SystemClient) GetMetadata(ctx context.Context, options ...RequestOption) (SystemGetMetadataRes, error) {
	return sc.client.SystemGetMetadata(ctx, options...)
}

// GetNodesMetrics calls System_getNodesMetrics.
func (sc *SystemClient) GetNodesMetrics(ctx context.Context, options ...RequestOption) (SystemGetNodesMetricsRes, error) {
	return sc.client.SystemGetNodesMetrics(ctx, options...)
}

// GetNodesStatistics calls System_getNodesStatistics.
func (sc *SystemClient) GetNodesStatistics(ctx context.Context, options ...RequestOption) (SystemGetNodesStatisticsRes, error) {
	return sc.client.SystemGetNodesStatistics(ctx, options...)
}

// GetRecap calls System_getRecap.
func (sc *SystemClient) GetRecap(ctx context.Context, options ...RequestOption) (SystemGetRecapRes, error) {
	return sc.client.SystemGetRecap(ctx, options...)
}

// GetRemnawaveHealth calls System_getRemnawaveHealth.
func (sc *SystemClient) GetRemnawaveHealth(ctx context.Context, options ...RequestOption) (SystemGetRemnawaveHealthRes, error) {
	return sc.client.SystemGetRemnawaveHealth(ctx, options...)
}

// GetStats calls System_getStats.
func (sc *SystemClient) GetStats(ctx context.Context, options ...RequestOption) (SystemGetStatsRes, error) {
	return sc.client.SystemGetStats(ctx, options...)
}

// GetStatsDigest calls System_getStatsDigest.
func (sc *SystemClient) GetStatsDigest(ctx context.Context, params SystemGetStatsDigestParams, options ...RequestOption) (SystemGetStatsDigestRes, error) {
	return sc.client.SystemGetStatsDigest(ctx, params, options...)
}

// GetX25519Keypairs calls System_getX25519Keypairs.
func (sc *SystemClient) GetX25519Keypairs(ctx context.Context, options ...RequestOption) (SystemGetX25519KeypairsRes, error) {
	return sc.client.SystemGetX25519Keypairs(ctx, options...)
}

// TorrentBlockerReportsClient provides TorrentBlockerReports operations.
type TorrentBlockerReportsClient struct {
	client *Client
}

// NewTorrentBlockerReportsClient creates a new TorrentBlockerReportsClient.
func NewTorrentBlockerReportsClient(client *Client) *TorrentBlockerReportsClient {
	return &TorrentBlockerReportsClient{client: client}
}

// GetTorrentBlockerReportsWithParams calls TorrentBlockerReports_getTorrentBlockerReports.
func (sc *TorrentBlockerReportsClient) GetTorrentBlockerReportsWithParams(ctx context.Context, params TorrentBlockerReportsGetTorrentBlockerReportsParams, options ...RequestOption) (TorrentBlockerReportsGetTorrentBlockerReportsRes, error) {
	return sc.client.TorrentBlockerReportsGetTorrentBlockerReports(ctx, params, options...)
}

// GetTorrentBlockerReports lists results with simple offset pagination.
func (sc *TorrentBlockerReportsClient) GetTorrentBlockerReports(ctx context.Context, start int, size int, options ...RequestOption) (TorrentBlockerReportsGetTorrentBlockerReportsRes, error) {
	return sc.GetTorrentBlockerReportsWithParams(ctx, TorrentBlockerReportsGetTorrentBlockerReportsParams{
		Start: NewOptInt(start),
		Size:  NewOptInt(size),
	}, options...)
}

// GetTorrentBlockerReportsStats calls TorrentBlockerReports_getTorrentBlockerReportsStats.
func (sc *TorrentBlockerReportsClient) GetTorrentBlockerReportsStats(ctx context.Context, options ...RequestOption) (TorrentBlockerReportsGetTorrentBlockerReportsStatsRes, error) {
	return sc.client.TorrentBlockerReportsGetTorrentBlockerReportsStats(ctx, options...)
}

// TruncateTorrentBlockerReports calls TorrentBlockerReports_truncateTorrentBlockerReports.
func (sc *TorrentBlockerReportsClient) TruncateTorrentBlockerReports(ctx context.Context, options ...RequestOption) (TorrentBlockerReportsTruncateTorrentBlockerReportsRes, error) {
	return sc.client.TorrentBlockerReportsTruncateTorrentBlockerReports(ctx, options...)
}

// UserSubscriptionRequestHistoryClient provides UserSubscriptionRequestHistory operations.
type UserSubscriptionRequestHistoryClient struct {
	client *Client
}

// NewUserSubscriptionRequestHistoryClient creates a new UserSubscriptionRequestHistoryClient.
func NewUserSubscriptionRequestHistoryClient(client *Client) *UserSubscriptionRequestHistoryClient {
	return &UserSubscriptionRequestHistoryClient{client: client}
}

// GetSubscriptionRequestHistoryWithParams calls UserSubscriptionRequestHistory_getSubscriptionRequestHistory.
func (sc *UserSubscriptionRequestHistoryClient) GetSubscriptionRequestHistoryWithParams(ctx context.Context, params UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryParams, options ...RequestOption) (UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes, error) {
	return sc.client.UserSubscriptionRequestHistoryGetSubscriptionRequestHistory(ctx, params, options...)
}

// GetSubscriptionRequestHistory lists results with simple offset pagination.
func (sc *UserSubscriptionRequestHistoryClient) GetSubscriptionRequestHistory(ctx context.Context, start int, size int, options ...RequestOption) (UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes, error) {
	return sc.GetSubscriptionRequestHistoryWithParams(ctx, UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryParams{
		Start: NewOptInt(start),
		Size:  NewOptInt(size),
	}, options...)
}

// GetSubscriptionRequestHistoryStats calls UserSubscriptionRequestHistory_getSubscriptionRequestHistoryStats.
func (sc *UserSubscriptionRequestHistoryClient) GetSubscriptionRequestHistoryStats(ctx context.Context, options ...RequestOption) (UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsRes, error) {
	return sc.client.UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryStats(ctx, options...)
}

// UsersClient provides Users operations.
type UsersClient struct {
	client *Client
}

// NewUsersClient creates a new UsersClient.
func NewUsersClient(client *Client) *UsersClient {
	return &UsersClient{client: client}
}

// CreateUser calls Users_createUser.
func (sc *UsersClient) CreateUser(ctx context.Context, request *CreateUserBody, options ...RequestOption) (UsersCreateUserRes, error) {
	return sc.client.UsersCreateUser(ctx, request, options...)
}

// DeleteUser calls Users_deleteUser.
func (sc *UsersClient) DeleteUser(ctx context.Context, userid int, options ...RequestOption) (UsersDeleteUserRes, error) {

	return sc.client.UsersDeleteUser(ctx, UsersDeleteUserParams{
		UserId: userid,
	}, options...)
}

// DisableUser calls Users_disableUser.
func (sc *UsersClient) DisableUser(ctx context.Context, userid int, options ...RequestOption) (UsersDisableUserRes, error) {

	return sc.client.UsersDisableUser(ctx, UsersDisableUserParams{
		UserId: userid,
	}, options...)
}

// EnableUser calls Users_enableUser.
func (sc *UsersClient) EnableUser(ctx context.Context, userid int, options ...RequestOption) (UsersEnableUserRes, error) {

	return sc.client.UsersEnableUser(ctx, UsersEnableUserParams{
		UserId: userid,
	}, options...)
}

// ExtendUserExpirationDate calls Users_extendUserExpirationDate.
func (sc *UsersClient) ExtendUserExpirationDate(ctx context.Context, request *ExtendUserBody, userid int, options ...RequestOption) (UsersExtendUserExpirationDateRes, error) {

	return sc.client.UsersExtendUserExpirationDate(ctx, request, UsersExtendUserExpirationDateParams{
		UserId: userid,
	}, options...)
}

// GetUserAccessibleNodes calls Users_getUserAccessibleNodes.
func (sc *UsersClient) GetUserAccessibleNodes(ctx context.Context, userid int, options ...RequestOption) (UsersGetUserAccessibleNodesRes, error) {

	return sc.client.UsersGetUserAccessibleNodes(ctx, UsersGetUserAccessibleNodesParams{
		UserId: userid,
	}, options...)
}

// GetUserById calls Users_getUserById.
func (sc *UsersClient) GetUserById(ctx context.Context, userid int, options ...RequestOption) (UsersGetUserByIdRes, error) {

	return sc.client.UsersGetUserById(ctx, UsersGetUserByIdParams{
		UserId: userid,
	}, options...)
}

// GetUserByShortUuid calls Users_getUserByShortUuid.
func (sc *UsersClient) GetUserByShortUuid(ctx context.Context, shortuuid string, options ...RequestOption) (UsersGetUserByShortUuidRes, error) {

	return sc.client.UsersGetUserByShortUuid(ctx, UsersGetUserByShortUuidParams{
		ShortUuid: shortuuid,
	}, options...)
}

// GetUserByUsername calls Users_getUserByUsername.
func (sc *UsersClient) GetUserByUsername(ctx context.Context, username string, options ...RequestOption) (UsersGetUserByUsernameRes, error) {

	return sc.client.UsersGetUserByUsername(ctx, UsersGetUserByUsernameParams{
		Username: username,
	}, options...)
}

// GetUserSubscriptionRequestHistory calls Users_getUserSubscriptionRequestHistory.
func (sc *UsersClient) GetUserSubscriptionRequestHistory(ctx context.Context, userid int, options ...RequestOption) (UsersGetUserSubscriptionRequestHistoryRes, error) {

	return sc.client.UsersGetUserSubscriptionRequestHistory(ctx, UsersGetUserSubscriptionRequestHistoryParams{
		UserId: userid,
	}, options...)
}

// GetUsersWithParams calls Users_getUsers.
func (sc *UsersClient) GetUsersWithParams(ctx context.Context, params UsersGetUsersParams, options ...RequestOption) (UsersGetUsersRes, error) {
	return sc.client.UsersGetUsers(ctx, params, options...)
}

// GetUsers lists results with simple offset pagination.
func (sc *UsersClient) GetUsers(ctx context.Context, start int, size int, options ...RequestOption) (UsersGetUsersRes, error) {
	return sc.GetUsersWithParams(ctx, UsersGetUsersParams{
		Start: NewOptInt(start),
		Size:  NewOptInt(size),
	}, options...)
}

// GetUsersStream calls Users_getUsersStream.
func (sc *UsersClient) GetUsersStream(ctx context.Context, params UsersGetUsersStreamParams, options ...RequestOption) (UsersGetUsersStreamRes, error) {
	return sc.client.UsersGetUsersStream(ctx, params, options...)
}

// GetUsersTags calls Users_getUsersTags.
func (sc *UsersClient) GetUsersTags(ctx context.Context, options ...RequestOption) (UsersGetUsersTagsRes, error) {
	return sc.client.UsersGetUsersTags(ctx, options...)
}

// ResetUserTraffic calls Users_resetUserTraffic.
func (sc *UsersClient) ResetUserTraffic(ctx context.Context, userid int, options ...RequestOption) (UsersResetUserTrafficRes, error) {

	return sc.client.UsersResetUserTraffic(ctx, UsersResetUserTrafficParams{
		UserId: userid,
	}, options...)
}

// ResolveUser calls Users_resolveUser.
func (sc *UsersClient) ResolveUser(ctx context.Context, request *ResolveUserBody, options ...RequestOption) (UsersResolveUserRes, error) {
	return sc.client.UsersResolveUser(ctx, request, options...)
}

// RevokeUserSubscription calls Users_revokeUserSubscription.
func (sc *UsersClient) RevokeUserSubscription(ctx context.Context, request *RevokeUserSubscriptionBody, userid int, options ...RequestOption) (UsersRevokeUserSubscriptionRes, error) {

	return sc.client.UsersRevokeUserSubscription(ctx, request, UsersRevokeUserSubscriptionParams{
		UserId: userid,
	}, options...)
}

// UpdateUser calls Users_updateUser.
func (sc *UsersClient) UpdateUser(ctx context.Context, request *UpdateUserBody, options ...RequestOption) (UsersUpdateUserRes, error) {
	return sc.client.UsersUpdateUser(ctx, request, options...)
}

// UsersBulkActionsClient provides UsersBulkActions operations.
type UsersBulkActionsClient struct {
	client *Client
}

// NewUsersBulkActionsClient creates a new UsersBulkActionsClient.
func NewUsersBulkActionsClient(client *Client) *UsersBulkActionsClient {
	return &UsersBulkActionsClient{client: client}
}

// BulkAllExtendExpirationDate calls UsersBulkActions_bulkAllExtendExpirationDate.
func (sc *UsersBulkActionsClient) BulkAllExtendExpirationDate(ctx context.Context, request *BulkAllExtendExpirationDateBody, options ...RequestOption) (UsersBulkActionsBulkAllExtendExpirationDateRes, error) {
	return sc.client.UsersBulkActionsBulkAllExtendExpirationDate(ctx, request, options...)
}

// BulkAllResetUserTraffic calls UsersBulkActions_bulkAllResetUserTraffic.
func (sc *UsersBulkActionsClient) BulkAllResetUserTraffic(ctx context.Context, options ...RequestOption) (UsersBulkActionsBulkAllResetUserTrafficRes, error) {
	return sc.client.UsersBulkActionsBulkAllResetUserTraffic(ctx, options...)
}

// BulkDeleteUsers calls UsersBulkActions_bulkDeleteUsers.
func (sc *UsersBulkActionsClient) BulkDeleteUsers(ctx context.Context, request *UsersBodyBulkRequest, options ...RequestOption) (UsersBulkActionsBulkDeleteUsersRes, error) {
	return sc.client.UsersBulkActionsBulkDeleteUsers(ctx, request, options...)
}

// BulkDeleteUsersByStatus calls UsersBulkActions_bulkDeleteUsersByStatus.
func (sc *UsersBulkActionsClient) BulkDeleteUsersByStatus(ctx context.Context, request *BulkDeleteUsersByStatusBody, options ...RequestOption) (UsersBulkActionsBulkDeleteUsersByStatusRes, error) {
	return sc.client.UsersBulkActionsBulkDeleteUsersByStatus(ctx, request, options...)
}

// BulkExtendExpirationDate calls UsersBulkActions_bulkExtendExpirationDate.
func (sc *UsersBulkActionsClient) BulkExtendExpirationDate(ctx context.Context, request *BulkExtendExpirationDateBody, options ...RequestOption) (UsersBulkActionsBulkExtendExpirationDateRes, error) {
	return sc.client.UsersBulkActionsBulkExtendExpirationDate(ctx, request, options...)
}

// BulkResetUserTraffic calls UsersBulkActions_bulkResetUserTraffic.
func (sc *UsersBulkActionsClient) BulkResetUserTraffic(ctx context.Context, request *UsersBodyBulkRequest, options ...RequestOption) (UsersBulkActionsBulkResetUserTrafficRes, error) {
	return sc.client.UsersBulkActionsBulkResetUserTraffic(ctx, request, options...)
}

// BulkRevokeUsersSubscription calls UsersBulkActions_bulkRevokeUsersSubscription.
func (sc *UsersBulkActionsClient) BulkRevokeUsersSubscription(ctx context.Context, request *UsersBodyBulkRequest, options ...RequestOption) (UsersBulkActionsBulkRevokeUsersSubscriptionRes, error) {
	return sc.client.UsersBulkActionsBulkRevokeUsersSubscription(ctx, request, options...)
}

// BulkUpdateAllUsers calls UsersBulkActions_bulkUpdateAllUsers.
func (sc *UsersBulkActionsClient) BulkUpdateAllUsers(ctx context.Context, request *BulkAllUpdateUsersBody, options ...RequestOption) (UsersBulkActionsBulkUpdateAllUsersRes, error) {
	return sc.client.UsersBulkActionsBulkUpdateAllUsers(ctx, request, options...)
}

// BulkUpdateUsers calls UsersBulkActions_bulkUpdateUsers.
func (sc *UsersBulkActionsClient) BulkUpdateUsers(ctx context.Context, request *BulkUpdateUsersBody, options ...RequestOption) (UsersBulkActionsBulkUpdateUsersRes, error) {
	return sc.client.UsersBulkActionsBulkUpdateUsers(ctx, request, options...)
}

// BulkUpdateUsersInternalSquads calls UsersBulkActions_bulkUpdateUsersInternalSquads.
func (sc *UsersBulkActionsClient) BulkUpdateUsersInternalSquads(ctx context.Context, request *BulkUpdateUsersSquadsBody, options ...RequestOption) (UsersBulkActionsBulkUpdateUsersInternalSquadsRes, error) {
	return sc.client.UsersBulkActionsBulkUpdateUsersInternalSquads(ctx, request, options...)
}
