// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Authorization provides Authorization security value.
	// JWT obtained login.
	Authorization(ctx context.Context, operationName OperationName) (Authorization, error)
}

// operationRolesAuthorization is a private map storing roles per operation.
var operationRolesAuthorization = map[string][]string{
	ApiTokensCreateApiTokenOperation:                                          []string{},
	ApiTokensDeleteApiTokenOperation:                                          []string{},
	ApiTokensGetApiTokensOperation:                                            []string{},
	ApiTokensGetScopesOperation:                                               []string{},
	BandwidthStatsNodesGetNodeUsageOperation:                                  []string{},
	BandwidthStatsNodesGetStatsNodeUsersUsageOperation:                        []string{},
	BandwidthStatsNodesGetStatsNodesUsersUsageOperation:                       []string{},
	BandwidthStatsUsersGetStatsNodesUsageOperation:                            []string{},
	ConfigProfileCreateConfigProfileOperation:                                 []string{},
	ConfigProfileDeleteConfigProfileByUuidOperation:                           []string{},
	ConfigProfileGetAllInboundsOperation:                                      []string{},
	ConfigProfileGetComputedConfigProfileByUuidOperation:                      []string{},
	ConfigProfileGetConfigProfileByUuidOperation:                              []string{},
	ConfigProfileGetConfigProfilesOperation:                                   []string{},
	ConfigProfileGetInboundsByProfileUuidOperation:                            []string{},
	ConfigProfileGetTagsOperation:                                             []string{},
	ConfigProfileReorderConfigProfilesOperation:                               []string{},
	ConfigProfileSetTagsOperation:                                             []string{},
	ConfigProfileUpdateConfigProfileOperation:                                 []string{},
	ConnectionsConnectionsByNodeOperation:                                     []string{},
	ConnectionsConnectionsByNodeResultOperation:                               []string{},
	ConnectionsConnectionsByUserOperation:                                     []string{},
	ConnectionsConnectionsByUserResultOperation:                               []string{},
	ConnectionsDropConnectionsOperation:                                       []string{},
	ConnectionsGeocheckByNodeOperation:                                        []string{},
	ConnectionsGeocheckByNodeResultOperation:                                  []string{},
	ExternalSquadAddUsersToExternalSquadOperation:                             []string{},
	ExternalSquadCreateExternalSquadOperation:                                 []string{},
	ExternalSquadDeleteExternalSquadOperation:                                 []string{},
	ExternalSquadGetExternalSquadByUuidOperation:                              []string{},
	ExternalSquadGetExternalSquadsOperation:                                   []string{},
	ExternalSquadGetTagsOperation:                                             []string{},
	ExternalSquadRemoveUsersFromExternalSquadOperation:                        []string{},
	ExternalSquadReorderExternalSquadsOperation:                               []string{},
	ExternalSquadSetTagsOperation:                                             []string{},
	ExternalSquadUpdateExternalSquadOperation:                                 []string{},
	HostsBulkActionsDeleteHostsOperation:                                      []string{},
	HostsBulkActionsDisableHostsOperation:                                     []string{},
	HostsBulkActionsEnableHostsOperation:                                      []string{},
	HostsBulkActionsSetPortToHostsOperation:                                   []string{},
	HostsCreateHostOperation:                                                  []string{},
	HostsDeleteHostOperation:                                                  []string{},
	HostsGetHostsOperation:                                                    []string{},
	HostsGetHostsTagsOperation:                                                []string{},
	HostsGetOneHostOperation:                                                  []string{},
	HostsReorderHostsOperation:                                                []string{},
	HostsUpdateHostOperation:                                                  []string{},
	HwidUserDevicesCreateUserHwidDeviceOperation:                              []string{},
	HwidUserDevicesDeleteAllUserHwidDevicesOperation:                          []string{},
	HwidUserDevicesDeleteUserHwidDeviceOperation:                              []string{},
	HwidUserDevicesGetAllUsersOperation:                                       []string{},
	HwidUserDevicesGetHwidDevicesStatsOperation:                               []string{},
	HwidUserDevicesGetTopUsersByHwidDevicesOperation:                          []string{},
	HwidUserDevicesGetUserHwidDevicesOperation:                                []string{},
	InfraBillingCreateInfraBillingNodeOperation:                               []string{},
	InfraBillingCreateInfraBillingRecordOperation:                             []string{},
	InfraBillingCreateInfraProviderOperation:                                  []string{},
	InfraBillingDeleteInfraBillingNodeOperation:                               []string{},
	InfraBillingDeleteInfraBillingRecordOperation:                             []string{},
	InfraBillingDelteInfraProviderOperation:                                   []string{},
	InfraBillingGetBillingNodesOperation:                                      []string{},
	InfraBillingGetInfraBillingRecordsOperation:                               []string{},
	InfraBillingGetInfraProviderOperation:                                     []string{},
	InfraBillingGetInfraProvidersOperation:                                    []string{},
	InfraBillingUpdateInfraBillingNodeOperation:                               []string{},
	InfraBillingUpdateInfraProviderOperation:                                  []string{},
	InternalSquadAddManyUsersToInternalSquadOperation:                         []string{},
	InternalSquadAddUsersToInternalSquadOperation:                             []string{},
	InternalSquadCreateInternalSquadOperation:                                 []string{},
	InternalSquadDeleteInternalSquadOperation:                                 []string{},
	InternalSquadGetInternalSquadAccessibleNodesOperation:                     []string{},
	InternalSquadGetInternalSquadByUuidOperation:                              []string{},
	InternalSquadGetInternalSquadUsageOperation:                               []string{},
	InternalSquadGetInternalSquadsOperation:                                   []string{},
	InternalSquadGetTagsOperation:                                             []string{},
	InternalSquadRemoveManyUsersFromInternalSquadOperation:                    []string{},
	InternalSquadRemoveUsersFromInternalSquadOperation:                        []string{},
	InternalSquadReorderInternalSquadsOperation:                               []string{},
	InternalSquadSetTagsOperation:                                             []string{},
	InternalSquadStatsGetInternalSquadUsageOperation:                          []string{},
	InternalSquadStatsGetInternalSquadUserUsageOperation:                      []string{},
	InternalSquadUpdateInternalSquadOperation:                                 []string{},
	KeygenGenerateKeyOperation:                                                []string{},
	MetadataGetNodeMetadataOperation:                                          []string{},
	MetadataGetUserMetadataOperation:                                          []string{},
	MetadataUpsertNodeMetadataOperation:                                       []string{},
	MetadataUpsertUserMetadataOperation:                                       []string{},
	NodeIntegrationCreateIntegrationOperation:                                 []string{},
	NodeIntegrationDeleteIntegrationOperation:                                 []string{},
	NodeIntegrationGetAllIntegrationsOperation:                                []string{},
	NodeIntegrationGetIntegrationByUuidOperation:                              []string{},
	NodeIntegrationUpdateIntegrationOperation:                                 []string{},
	NodePluginCloneNodePluginOperation:                                        []string{},
	NodePluginCreateConfigOperation:                                           []string{},
	NodePluginCreateSharedListOperation:                                       []string{},
	NodePluginDeleteConfigOperation:                                           []string{},
	NodePluginDeleteSharedListOperation:                                       []string{},
	NodePluginGetAllConfigsOperation:                                          []string{},
	NodePluginGetAllSharedListsOperation:                                      []string{},
	NodePluginGetConfigByUuidOperation:                                        []string{},
	NodePluginGetSharedListByNameOperation:                                    []string{},
	NodePluginGetTagsOperation:                                                []string{},
	NodePluginPluginExecutorOperation:                                         []string{},
	NodePluginReorderNodePluginsOperation:                                     []string{},
	NodePluginSetTagsOperation:                                                []string{},
	NodePluginSyncNodePluginOperation:                                         []string{},
	NodePluginSyncSharedListOperation:                                         []string{},
	NodePluginUpdateConfigOperation:                                           []string{},
	NodePluginUpdateSharedListOperation:                                       []string{},
	NodesBulkNodesActionsOperation:                                            []string{},
	NodesBulkNodesUpdateOperation:                                             []string{},
	NodesCreateNodeOperation:                                                  []string{},
	NodesDeleteNodeOperation:                                                  []string{},
	NodesDisableNodeOperation:                                                 []string{},
	NodesEnableNodeOperation:                                                  []string{},
	NodesGetNodeOperation:                                                     []string{},
	NodesGetNodesOperation:                                                    []string{},
	NodesGetNodesTagsOperation:                                                []string{},
	NodesProfileModificationOperation:                                         []string{},
	NodesReorderNodesOperation:                                                []string{},
	NodesResetNodeTrafficOperation:                                            []string{},
	NodesRestartAllNodesOperation:                                             []string{},
	NodesRestartNodeOperation:                                                 []string{},
	NodesUpdateNodeOperation:                                                  []string{},
	NodesUsageHistoryGetStatsNodesUsageOperation:                              []string{},
	PasskeyDeletePasskeyOperation:                                             []string{},
	PasskeyGetActivePasskeysOperation:                                         []string{},
	PasskeyPasskeyRegistrationOptionsOperation:                                []string{},
	PasskeyPasskeyRegistrationVerifyOperation:                                 []string{},
	PasskeyUpdatePasskeyOperation:                                             []string{},
	RemnawaveSettingsGetSettingsOperation:                                     []string{},
	RemnawaveSettingsUpdateSettingsOperation:                                  []string{},
	SnippetsCreateSnippetOperation:                                            []string{},
	SnippetsDeleteSnippetByNameOperation:                                      []string{},
	SnippetsGetSnippetsOperation:                                              []string{},
	SnippetsSyncSnippetOperation:                                              []string{},
	SnippetsUpdateSnippetOperation:                                            []string{},
	SubscriptionPageConfigCloneSubscriptionPageConfigOperation:                []string{},
	SubscriptionPageConfigCreateConfigOperation:                               []string{},
	SubscriptionPageConfigDeleteConfigOperation:                               []string{},
	SubscriptionPageConfigGetAllConfigsOperation:                              []string{},
	SubscriptionPageConfigGetConfigByUuidOperation:                            []string{},
	SubscriptionPageConfigGetTagsOperation:                                    []string{},
	SubscriptionPageConfigReorderSubscriptionPageConfigsOperation:             []string{},
	SubscriptionPageConfigSetTagsOperation:                                    []string{},
	SubscriptionPageConfigUpdateConfigOperation:                               []string{},
	SubscriptionSettingsGetSettingsOperation:                                  []string{},
	SubscriptionSettingsUpdateSettingsOperation:                               []string{},
	SubscriptionTemplateCreateTemplateOperation:                               []string{},
	SubscriptionTemplateDeleteTemplateOperation:                               []string{},
	SubscriptionTemplateGetAllTemplatesOperation:                              []string{},
	SubscriptionTemplateGetTagsOperation:                                      []string{},
	SubscriptionTemplateGetTemplateByUuidOperation:                            []string{},
	SubscriptionTemplateReorderSubscriptionTemplatesOperation:                 []string{},
	SubscriptionTemplateSetTagsOperation:                                      []string{},
	SubscriptionTemplateUpdateTemplateOperation:                               []string{},
	SubscriptionsGetAllSubscriptionsOperation:                                 []string{},
	SubscriptionsGetConnectionKeysByUserIdOperation:                           []string{},
	SubscriptionsGetRawSubscriptionByShortUuidOperation:                       []string{},
	SubscriptionsGetSubpageConfigByShortUuidOperation:                         []string{},
	SubscriptionsGetSubscriptionByShortUuidProtectedOperation:                 []string{},
	SubscriptionsGetSubscriptionByUsernameOperation:                           []string{},
	SubscriptionsGetSubscriptionByUuidOperation:                               []string{},
	SystemDebugSrrMatcherOperation:                                            []string{},
	SystemGetBandwidthStatsOperation:                                          []string{},
	SystemGetConfigurationOperation:                                           []string{},
	SystemGetHttpStatsOperation:                                               []string{},
	SystemGetMetadataOperation:                                                []string{},
	SystemGetNodesMetricsOperation:                                            []string{},
	SystemGetNodesStatisticsOperation:                                         []string{},
	SystemGetRecapOperation:                                                   []string{},
	SystemGetRemnawaveHealthOperation:                                         []string{},
	SystemGetStatsOperation:                                                   []string{},
	SystemGetStatsDigestOperation:                                             []string{},
	SystemGetX25519KeypairsOperation:                                          []string{},
	TorrentBlockerReportsGetTorrentBlockerReportsOperation:                    []string{},
	TorrentBlockerReportsGetTorrentBlockerReportsStatsOperation:               []string{},
	TorrentBlockerReportsTruncateTorrentBlockerReportsOperation:               []string{},
	UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryOperation:      []string{},
	UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsOperation: []string{},
	UsersBulkActionsBulkAllExtendExpirationDateOperation:                      []string{},
	UsersBulkActionsBulkAllResetUserTrafficOperation:                          []string{},
	UsersBulkActionsBulkDeleteUsersOperation:                                  []string{},
	UsersBulkActionsBulkDeleteUsersByStatusOperation:                          []string{},
	UsersBulkActionsBulkExtendExpirationDateOperation:                         []string{},
	UsersBulkActionsBulkResetUserTrafficOperation:                             []string{},
	UsersBulkActionsBulkRevokeUsersSubscriptionOperation:                      []string{},
	UsersBulkActionsBulkUpdateAllUsersOperation:                               []string{},
	UsersBulkActionsBulkUpdateUsersOperation:                                  []string{},
	UsersBulkActionsBulkUpdateUsersInternalSquadsOperation:                    []string{},
	UsersCreateUserOperation:                                                  []string{},
	UsersDeleteUserOperation:                                                  []string{},
	UsersDisableUserOperation:                                                 []string{},
	UsersEnableUserOperation:                                                  []string{},
	UsersExtendUserExpirationDateOperation:                                    []string{},
	UsersGetUserAccessibleNodesOperation:                                      []string{},
	UsersGetUserByIdOperation:                                                 []string{},
	UsersGetUserByShortUuidOperation:                                          []string{},
	UsersGetUserByUsernameOperation:                                           []string{},
	UsersGetUserSubscriptionRequestHistoryOperation:                           []string{},
	UsersGetUsersOperation:                                                    []string{},
	UsersGetUsersStreamOperation:                                              []string{},
	UsersGetUsersTagsOperation:                                                []string{},
	UsersResetUserTrafficOperation:                                            []string{},
	UsersResolveUserOperation:                                                 []string{},
	UsersRevokeUserSubscriptionOperation:                                      []string{},
	UsersUpdateUserOperation:                                                  []string{},
}

// GetRolesForAuthorization returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAuthorization(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAuthorization(operation string) []string {
	roles, ok := operationRolesAuthorization[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityAuthorization(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Authorization(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Authorization\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
