// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateApiTokenBody) setDefaults() {
	{
		var defaultVal0 []string
		{
			var defaultVal0Elem string

			val := string("*")
			defaultVal0Elem = val
			defaultVal0 = append(defaultVal0, defaultVal0Elem)
		}
		s.Scopes = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *CreateHostBody) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := CreateHostBodySecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
	{
		val := bool(false)
		s.ShuffleHost.SetTo(val)
	}
	{
		val := bool(false)
		s.MihomoX25519.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateNodeBody) setDefaults() {
	{
		val := bool(false)
		s.IsTrafficTrackingActive.SetTo(val)
	}
	{
		val := string("XX")
		s.CountryCode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateUserBody) setDefaults() {
	{
		val := CreateUserBodyStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := CreateUserBodyTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetHostsResponseResponseItem) setDefaults() {
	{
		val := GetHostsResponseResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HostResponseResponse) setDefaults() {
	{
		val := HostResponseResponseSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RevokeUserSubscriptionBody) setDefaults() {
	{
		val := bool(false)
		s.RevokeOnlyPasswords.SetTo(val)
	}
}
