// Code generated by ogen, DO NOT EDIT.
package api

type ApiTokensCreateApiTokenRes interface {
	apiTokensCreateApiTokenRes()
}

type ApiTokensDeleteApiTokenRes interface {
	apiTokensDeleteApiTokenRes()
}

type ApiTokensGetApiTokensRes interface {
	apiTokensGetApiTokensRes()
}

type ApiTokensGetScopesRes interface {
	apiTokensGetScopesRes()
}

type AuthGetStatusRes interface {
	authGetStatusRes()
}

type AuthLoginRes interface {
	authLoginRes()
}

type AuthOauth2AuthorizeRes interface {
	authOauth2AuthorizeRes()
}

type AuthOauth2CallbackRes interface {
	authOauth2CallbackRes()
}

type AuthPasskeyAuthenticationOptionsRes interface {
	authPasskeyAuthenticationOptionsRes()
}

type AuthPasskeyAuthenticationVerifyRes interface {
	authPasskeyAuthenticationVerifyRes()
}

type AuthRegisterRes interface {
	authRegisterRes()
}

type BandwidthStatsNodesGetNodeUsageRes interface {
	bandwidthStatsNodesGetNodeUsageRes()
}

type BandwidthStatsNodesGetStatsNodeUsersUsageRes interface {
	bandwidthStatsNodesGetStatsNodeUsersUsageRes()
}

type BandwidthStatsNodesGetStatsNodesUsersUsageRes interface {
	bandwidthStatsNodesGetStatsNodesUsersUsageRes()
}

type BandwidthStatsUsersGetStatsNodesUsageRes interface {
	bandwidthStatsUsersGetStatsNodesUsageRes()
}

type ConfigProfileCreateConfigProfileRes interface {
	configProfileCreateConfigProfileRes()
}

type ConfigProfileDeleteConfigProfileByUuidRes interface {
	configProfileDeleteConfigProfileByUuidRes()
}

type ConfigProfileGetAllInboundsRes interface {
	configProfileGetAllInboundsRes()
}

type ConfigProfileGetComputedConfigProfileByUuidRes interface {
	configProfileGetComputedConfigProfileByUuidRes()
}

type ConfigProfileGetConfigProfileByUuidRes interface {
	configProfileGetConfigProfileByUuidRes()
}

type ConfigProfileGetConfigProfilesRes interface {
	configProfileGetConfigProfilesRes()
}

type ConfigProfileGetInboundsByProfileUuidRes interface {
	configProfileGetInboundsByProfileUuidRes()
}

type ConfigProfileGetTagsRes interface {
	configProfileGetTagsRes()
}

type ConfigProfileReorderConfigProfilesRes interface {
	configProfileReorderConfigProfilesRes()
}

type ConfigProfileSetTagsRes interface {
	configProfileSetTagsRes()
}

type ConfigProfileUpdateConfigProfileRes interface {
	configProfileUpdateConfigProfileRes()
}

type ConnectionsConnectionsByNodeRes interface {
	connectionsConnectionsByNodeRes()
}

type ConnectionsConnectionsByNodeResultRes interface {
	connectionsConnectionsByNodeResultRes()
}

type ConnectionsConnectionsByUserRes interface {
	connectionsConnectionsByUserRes()
}

type ConnectionsConnectionsByUserResultRes interface {
	connectionsConnectionsByUserResultRes()
}

type ConnectionsDropConnectionsRes interface {
	connectionsDropConnectionsRes()
}

type ConnectionsGeocheckByNodeRes interface {
	connectionsGeocheckByNodeRes()
}

type ConnectionsGeocheckByNodeResultRes interface {
	connectionsGeocheckByNodeResultRes()
}

type ExternalSquadAddUsersToExternalSquadRes interface {
	externalSquadAddUsersToExternalSquadRes()
}

type ExternalSquadCreateExternalSquadRes interface {
	externalSquadCreateExternalSquadRes()
}

type ExternalSquadDeleteExternalSquadRes interface {
	externalSquadDeleteExternalSquadRes()
}

type ExternalSquadGetExternalSquadByUuidRes interface {
	externalSquadGetExternalSquadByUuidRes()
}

type ExternalSquadGetExternalSquadsRes interface {
	externalSquadGetExternalSquadsRes()
}

type ExternalSquadGetTagsRes interface {
	externalSquadGetTagsRes()
}

type ExternalSquadRemoveUsersFromExternalSquadRes interface {
	externalSquadRemoveUsersFromExternalSquadRes()
}

type ExternalSquadReorderExternalSquadsRes interface {
	externalSquadReorderExternalSquadsRes()
}

type ExternalSquadSetTagsRes interface {
	externalSquadSetTagsRes()
}

type ExternalSquadUpdateExternalSquadRes interface {
	externalSquadUpdateExternalSquadRes()
}

type HostsBulkActionsDeleteHostsRes interface {
	hostsBulkActionsDeleteHostsRes()
}

type HostsBulkActionsDisableHostsRes interface {
	hostsBulkActionsDisableHostsRes()
}

type HostsBulkActionsEnableHostsRes interface {
	hostsBulkActionsEnableHostsRes()
}

type HostsBulkActionsSetPortToHostsRes interface {
	hostsBulkActionsSetPortToHostsRes()
}

type HostsCreateHostRes interface {
	hostsCreateHostRes()
}

type HostsDeleteHostRes interface {
	hostsDeleteHostRes()
}

type HostsGetHostsRes interface {
	hostsGetHostsRes()
}

type HostsGetHostsTagsRes interface {
	hostsGetHostsTagsRes()
}

type HostsGetOneHostRes interface {
	hostsGetOneHostRes()
}

type HostsReorderHostsRes interface {
	hostsReorderHostsRes()
}

type HostsUpdateHostRes interface {
	hostsUpdateHostRes()
}

type HwidUserDevicesCreateUserHwidDeviceRes interface {
	hwidUserDevicesCreateUserHwidDeviceRes()
}

type HwidUserDevicesDeleteAllUserHwidDevicesRes interface {
	hwidUserDevicesDeleteAllUserHwidDevicesRes()
}

type HwidUserDevicesDeleteUserHwidDeviceRes interface {
	hwidUserDevicesDeleteUserHwidDeviceRes()
}

type HwidUserDevicesGetAllUsersRes interface {
	hwidUserDevicesGetAllUsersRes()
}

type HwidUserDevicesGetHwidDevicesStatsRes interface {
	hwidUserDevicesGetHwidDevicesStatsRes()
}

type HwidUserDevicesGetTopUsersByHwidDevicesRes interface {
	hwidUserDevicesGetTopUsersByHwidDevicesRes()
}

type HwidUserDevicesGetUserHwidDevicesRes interface {
	hwidUserDevicesGetUserHwidDevicesRes()
}

type InfraBillingCreateInfraBillingNodeRes interface {
	infraBillingCreateInfraBillingNodeRes()
}

type InfraBillingCreateInfraBillingRecordRes interface {
	infraBillingCreateInfraBillingRecordRes()
}

type InfraBillingCreateInfraProviderRes interface {
	infraBillingCreateInfraProviderRes()
}

type InfraBillingDeleteInfraBillingNodeRes interface {
	infraBillingDeleteInfraBillingNodeRes()
}

type InfraBillingDeleteInfraBillingRecordRes interface {
	infraBillingDeleteInfraBillingRecordRes()
}

type InfraBillingDelteInfraProviderRes interface {
	infraBillingDelteInfraProviderRes()
}

type InfraBillingGetBillingNodesRes interface {
	infraBillingGetBillingNodesRes()
}

type InfraBillingGetInfraBillingRecordsRes interface {
	infraBillingGetInfraBillingRecordsRes()
}

type InfraBillingGetInfraProviderRes interface {
	infraBillingGetInfraProviderRes()
}

type InfraBillingGetInfraProvidersRes interface {
	infraBillingGetInfraProvidersRes()
}

type InfraBillingUpdateInfraBillingNodeRes interface {
	infraBillingUpdateInfraBillingNodeRes()
}

type InfraBillingUpdateInfraProviderRes interface {
	infraBillingUpdateInfraProviderRes()
}

type InternalSquadAddManyUsersToInternalSquadRes interface {
	internalSquadAddManyUsersToInternalSquadRes()
}

type InternalSquadAddUsersToInternalSquadRes interface {
	internalSquadAddUsersToInternalSquadRes()
}

type InternalSquadCreateInternalSquadRes interface {
	internalSquadCreateInternalSquadRes()
}

type InternalSquadDeleteInternalSquadRes interface {
	internalSquadDeleteInternalSquadRes()
}

type InternalSquadGetInternalSquadAccessibleNodesRes interface {
	internalSquadGetInternalSquadAccessibleNodesRes()
}

type InternalSquadGetInternalSquadByUuidRes interface {
	internalSquadGetInternalSquadByUuidRes()
}

type InternalSquadGetInternalSquadUsageRes interface {
	internalSquadGetInternalSquadUsageRes()
}

type InternalSquadGetInternalSquadsRes interface {
	internalSquadGetInternalSquadsRes()
}

type InternalSquadGetTagsRes interface {
	internalSquadGetTagsRes()
}

type InternalSquadRemoveManyUsersFromInternalSquadRes interface {
	internalSquadRemoveManyUsersFromInternalSquadRes()
}

type InternalSquadRemoveUsersFromInternalSquadRes interface {
	internalSquadRemoveUsersFromInternalSquadRes()
}

type InternalSquadReorderInternalSquadsRes interface {
	internalSquadReorderInternalSquadsRes()
}

type InternalSquadSetTagsRes interface {
	internalSquadSetTagsRes()
}

type InternalSquadStatsGetInternalSquadUsageRes interface {
	internalSquadStatsGetInternalSquadUsageRes()
}

type InternalSquadStatsGetInternalSquadUserUsageRes interface {
	internalSquadStatsGetInternalSquadUserUsageRes()
}

type InternalSquadUpdateInternalSquadRes interface {
	internalSquadUpdateInternalSquadRes()
}

type KeygenGenerateKeyRes interface {
	keygenGenerateKeyRes()
}

type MetadataGetNodeMetadataRes interface {
	metadataGetNodeMetadataRes()
}

type MetadataGetUserMetadataRes interface {
	metadataGetUserMetadataRes()
}

type MetadataUpsertNodeMetadataRes interface {
	metadataUpsertNodeMetadataRes()
}

type MetadataUpsertUserMetadataRes interface {
	metadataUpsertUserMetadataRes()
}

type NodeIntegrationCreateIntegrationRes interface {
	nodeIntegrationCreateIntegrationRes()
}

type NodeIntegrationDeleteIntegrationRes interface {
	nodeIntegrationDeleteIntegrationRes()
}

type NodeIntegrationGetAllIntegrationsRes interface {
	nodeIntegrationGetAllIntegrationsRes()
}

type NodeIntegrationGetIntegrationByUuidRes interface {
	nodeIntegrationGetIntegrationByUuidRes()
}

type NodeIntegrationUpdateIntegrationRes interface {
	nodeIntegrationUpdateIntegrationRes()
}

type NodePluginCloneNodePluginRes interface {
	nodePluginCloneNodePluginRes()
}

type NodePluginCreateConfigRes interface {
	nodePluginCreateConfigRes()
}

type NodePluginCreateSharedListRes interface {
	nodePluginCreateSharedListRes()
}

type NodePluginDeleteConfigRes interface {
	nodePluginDeleteConfigRes()
}

type NodePluginDeleteSharedListRes interface {
	nodePluginDeleteSharedListRes()
}

type NodePluginGetAllConfigsRes interface {
	nodePluginGetAllConfigsRes()
}

type NodePluginGetAllSharedListsRes interface {
	nodePluginGetAllSharedListsRes()
}

type NodePluginGetConfigByUuidRes interface {
	nodePluginGetConfigByUuidRes()
}

type NodePluginGetSharedListByNameRes interface {
	nodePluginGetSharedListByNameRes()
}

type NodePluginGetTagsRes interface {
	nodePluginGetTagsRes()
}

type NodePluginPluginExecutorRes interface {
	nodePluginPluginExecutorRes()
}

type NodePluginReorderNodePluginsRes interface {
	nodePluginReorderNodePluginsRes()
}

type NodePluginSetTagsRes interface {
	nodePluginSetTagsRes()
}

type NodePluginSyncNodePluginRes interface {
	nodePluginSyncNodePluginRes()
}

type NodePluginSyncSharedListRes interface {
	nodePluginSyncSharedListRes()
}

type NodePluginUpdateConfigRes interface {
	nodePluginUpdateConfigRes()
}

type NodePluginUpdateSharedListRes interface {
	nodePluginUpdateSharedListRes()
}

type NodesBulkNodesActionsRes interface {
	nodesBulkNodesActionsRes()
}

type NodesBulkNodesUpdateRes interface {
	nodesBulkNodesUpdateRes()
}

type NodesCreateNodeRes interface {
	nodesCreateNodeRes()
}

type NodesDeleteNodeRes interface {
	nodesDeleteNodeRes()
}

type NodesDisableNodeRes interface {
	nodesDisableNodeRes()
}

type NodesEnableNodeRes interface {
	nodesEnableNodeRes()
}

type NodesGetNodeRes interface {
	nodesGetNodeRes()
}

type NodesGetNodesRes interface {
	nodesGetNodesRes()
}

type NodesGetNodesTagsRes interface {
	nodesGetNodesTagsRes()
}

type NodesProfileModificationRes interface {
	nodesProfileModificationRes()
}

type NodesReorderNodesRes interface {
	nodesReorderNodesRes()
}

type NodesResetNodeTrafficRes interface {
	nodesResetNodeTrafficRes()
}

type NodesRestartAllNodesRes interface {
	nodesRestartAllNodesRes()
}

type NodesRestartNodeRes interface {
	nodesRestartNodeRes()
}

type NodesUpdateNodeRes interface {
	nodesUpdateNodeRes()
}

type NodesUsageHistoryGetStatsNodesUsageRes interface {
	nodesUsageHistoryGetStatsNodesUsageRes()
}

type PasskeyDeletePasskeyRes interface {
	passkeyDeletePasskeyRes()
}

type PasskeyGetActivePasskeysRes interface {
	passkeyGetActivePasskeysRes()
}

type PasskeyPasskeyRegistrationOptionsRes interface {
	passkeyPasskeyRegistrationOptionsRes()
}

type PasskeyPasskeyRegistrationVerifyRes interface {
	passkeyPasskeyRegistrationVerifyRes()
}

type PasskeyUpdatePasskeyRes interface {
	passkeyUpdatePasskeyRes()
}

type RemnawaveSettingsGetSettingsRes interface {
	remnawaveSettingsGetSettingsRes()
}

type RemnawaveSettingsUpdateSettingsRes interface {
	remnawaveSettingsUpdateSettingsRes()
}

type SnippetsCreateSnippetRes interface {
	snippetsCreateSnippetRes()
}

type SnippetsDeleteSnippetByNameRes interface {
	snippetsDeleteSnippetByNameRes()
}

type SnippetsGetSnippetsRes interface {
	snippetsGetSnippetsRes()
}

type SnippetsSyncSnippetRes interface {
	snippetsSyncSnippetRes()
}

type SnippetsUpdateSnippetRes interface {
	snippetsUpdateSnippetRes()
}

type SubscriptionGetSubscriptionByClientTypeRes interface {
	subscriptionGetSubscriptionByClientTypeRes()
}

type SubscriptionGetSubscriptionInfoByShortUuidRes interface {
	subscriptionGetSubscriptionInfoByShortUuidRes()
}

type SubscriptionGetSubscriptionRes interface {
	subscriptionGetSubscriptionRes()
}

type SubscriptionPageConfigCloneSubscriptionPageConfigRes interface {
	subscriptionPageConfigCloneSubscriptionPageConfigRes()
}

type SubscriptionPageConfigCreateConfigRes interface {
	subscriptionPageConfigCreateConfigRes()
}

type SubscriptionPageConfigDeleteConfigRes interface {
	subscriptionPageConfigDeleteConfigRes()
}

type SubscriptionPageConfigGetAllConfigsRes interface {
	subscriptionPageConfigGetAllConfigsRes()
}

type SubscriptionPageConfigGetConfigByUuidRes interface {
	subscriptionPageConfigGetConfigByUuidRes()
}

type SubscriptionPageConfigGetTagsRes interface {
	subscriptionPageConfigGetTagsRes()
}

type SubscriptionPageConfigReorderSubscriptionPageConfigsRes interface {
	subscriptionPageConfigReorderSubscriptionPageConfigsRes()
}

type SubscriptionPageConfigSetTagsRes interface {
	subscriptionPageConfigSetTagsRes()
}

type SubscriptionPageConfigUpdateConfigRes interface {
	subscriptionPageConfigUpdateConfigRes()
}

type SubscriptionSettingsGetSettingsRes interface {
	subscriptionSettingsGetSettingsRes()
}

type SubscriptionSettingsUpdateSettingsRes interface {
	subscriptionSettingsUpdateSettingsRes()
}

type SubscriptionTemplateCreateTemplateRes interface {
	subscriptionTemplateCreateTemplateRes()
}

type SubscriptionTemplateDeleteTemplateRes interface {
	subscriptionTemplateDeleteTemplateRes()
}

type SubscriptionTemplateGetAllTemplatesRes interface {
	subscriptionTemplateGetAllTemplatesRes()
}

type SubscriptionTemplateGetTagsRes interface {
	subscriptionTemplateGetTagsRes()
}

type SubscriptionTemplateGetTemplateByUuidRes interface {
	subscriptionTemplateGetTemplateByUuidRes()
}

type SubscriptionTemplateReorderSubscriptionTemplatesRes interface {
	subscriptionTemplateReorderSubscriptionTemplatesRes()
}

type SubscriptionTemplateSetTagsRes interface {
	subscriptionTemplateSetTagsRes()
}

type SubscriptionTemplateUpdateTemplateRes interface {
	subscriptionTemplateUpdateTemplateRes()
}

type SubscriptionsGetAllSubscriptionsRes interface {
	subscriptionsGetAllSubscriptionsRes()
}

type SubscriptionsGetConnectionKeysByUserIdRes interface {
	subscriptionsGetConnectionKeysByUserIdRes()
}

type SubscriptionsGetRawSubscriptionByShortUuidRes interface {
	subscriptionsGetRawSubscriptionByShortUuidRes()
}

type SubscriptionsGetSubpageConfigByShortUuidRes interface {
	subscriptionsGetSubpageConfigByShortUuidRes()
}

type SubscriptionsGetSubscriptionByShortUuidProtectedRes interface {
	subscriptionsGetSubscriptionByShortUuidProtectedRes()
}

type SubscriptionsGetSubscriptionByUsernameRes interface {
	subscriptionsGetSubscriptionByUsernameRes()
}

type SubscriptionsGetSubscriptionByUuidRes interface {
	subscriptionsGetSubscriptionByUuidRes()
}

type SystemDebugSrrMatcherRes interface {
	systemDebugSrrMatcherRes()
}

type SystemGetBandwidthStatsRes interface {
	systemGetBandwidthStatsRes()
}

type SystemGetConfigurationRes interface {
	systemGetConfigurationRes()
}

type SystemGetHttpStatsRes interface {
	systemGetHttpStatsRes()
}

type SystemGetMetadataRes interface {
	systemGetMetadataRes()
}

type SystemGetNodesMetricsRes interface {
	systemGetNodesMetricsRes()
}

type SystemGetNodesStatisticsRes interface {
	systemGetNodesStatisticsRes()
}

type SystemGetRecapRes interface {
	systemGetRecapRes()
}

type SystemGetRemnawaveHealthRes interface {
	systemGetRemnawaveHealthRes()
}

type SystemGetStatsDigestRes interface {
	systemGetStatsDigestRes()
}

type SystemGetStatsRes interface {
	systemGetStatsRes()
}

type SystemGetX25519KeypairsRes interface {
	systemGetX25519KeypairsRes()
}

type TorrentBlockerReportsGetTorrentBlockerReportsRes interface {
	torrentBlockerReportsGetTorrentBlockerReportsRes()
}

type TorrentBlockerReportsGetTorrentBlockerReportsStatsRes interface {
	torrentBlockerReportsGetTorrentBlockerReportsStatsRes()
}

type TorrentBlockerReportsTruncateTorrentBlockerReportsRes interface {
	torrentBlockerReportsTruncateTorrentBlockerReportsRes()
}

type UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes interface {
	userSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes()
}

type UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsRes interface {
	userSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsRes()
}

type UsersBulkActionsBulkAllExtendExpirationDateRes interface {
	usersBulkActionsBulkAllExtendExpirationDateRes()
}

type UsersBulkActionsBulkAllResetUserTrafficRes interface {
	usersBulkActionsBulkAllResetUserTrafficRes()
}

type UsersBulkActionsBulkDeleteUsersByStatusRes interface {
	usersBulkActionsBulkDeleteUsersByStatusRes()
}

type UsersBulkActionsBulkDeleteUsersRes interface {
	usersBulkActionsBulkDeleteUsersRes()
}

type UsersBulkActionsBulkExtendExpirationDateRes interface {
	usersBulkActionsBulkExtendExpirationDateRes()
}

type UsersBulkActionsBulkResetUserTrafficRes interface {
	usersBulkActionsBulkResetUserTrafficRes()
}

type UsersBulkActionsBulkRevokeUsersSubscriptionRes interface {
	usersBulkActionsBulkRevokeUsersSubscriptionRes()
}

type UsersBulkActionsBulkUpdateAllUsersRes interface {
	usersBulkActionsBulkUpdateAllUsersRes()
}

type UsersBulkActionsBulkUpdateUsersInternalSquadsRes interface {
	usersBulkActionsBulkUpdateUsersInternalSquadsRes()
}

type UsersBulkActionsBulkUpdateUsersRes interface {
	usersBulkActionsBulkUpdateUsersRes()
}

type UsersCreateUserRes interface {
	usersCreateUserRes()
}

type UsersDeleteUserRes interface {
	usersDeleteUserRes()
}

type UsersDisableUserRes interface {
	usersDisableUserRes()
}

type UsersEnableUserRes interface {
	usersEnableUserRes()
}

type UsersExtendUserExpirationDateRes interface {
	usersExtendUserExpirationDateRes()
}

type UsersGetUserAccessibleNodesRes interface {
	usersGetUserAccessibleNodesRes()
}

type UsersGetUserByIdRes interface {
	usersGetUserByIdRes()
}

type UsersGetUserByShortUuidRes interface {
	usersGetUserByShortUuidRes()
}

type UsersGetUserByUsernameRes interface {
	usersGetUserByUsernameRes()
}

type UsersGetUserSubscriptionRequestHistoryRes interface {
	usersGetUserSubscriptionRequestHistoryRes()
}

type UsersGetUsersRes interface {
	usersGetUsersRes()
}

type UsersGetUsersStreamRes interface {
	usersGetUsersStreamRes()
}

type UsersGetUsersTagsRes interface {
	usersGetUsersTagsRes()
}

type UsersResetUserTrafficRes interface {
	usersResetUserTrafficRes()
}

type UsersResolveUserRes interface {
	usersResolveUserRes()
}

type UsersRevokeUserSubscriptionRes interface {
	usersRevokeUserSubscriptionRes()
}

type UsersUpdateUserRes interface {
	usersUpdateUserRes()
}
